/* NOREYO V8.92 — cancellation-policy truth.
   RFN means refundable, not automatically "free cancellation until >= 7 days".
   Preserve LiteAPI cancellationPolicies on mapped rate options and enforce the
   strict Preis2 criterion only when the actual positive-fee deadline supports it. */
(function(){
'use strict';
const BUILD='8.92',REQUIRED_FREE_DAYS=7;
let observer=null,raf=0,extractInstalled=false,filterInstalled=false,criteriaInstalled=false;
function norm(v){return String(v||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');}
function isoDatePart(v){const m=String(v||'').match(/^(\d{4}-\d{2}-\d{2})/);return m?m[1]:'';}
function validISO(v){const s=String(v||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;const d=new Date(s+'T12:00:00');return !Number.isNaN(d.getTime())&&d.getFullYear()===+s.slice(0,4)&&d.getMonth()+1===+s.slice(5,7)&&d.getDate()===+s.slice(8,10);}
function addDays(iso,days){if(!validISO(iso))return'';const d=new Date(iso+'T12:00:00');d.setDate(d.getDate()+days);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function policyInfos(policy){return Array.isArray(policy?.cancelPolicyInfos)?policy.cancelPolicyInfos:[];}
function positivePolicies(policy){return policyInfos(policy).filter(x=>Number(x?.amount)>0&&validISO(isoDatePart(x?.cancelTime))).sort((a,b)=>isoDatePart(a.cancelTime).localeCompare(isoDatePart(b.cancelTime)));}
function cancellationAssessment(policy,checkin,requiredDays=REQUIRED_FREE_DAYS){const tag=String(policy?.refundableTag||'').trim().toUpperCase();if(tag==='NRFN')return{verified:true,refundable:false,qualifies:false,reason:'non-refundable'};if(tag!=='RFN')return{verified:false,refundable:null,qualifies:false,reason:'missing-refundable-tag'};if(!validISO(checkin))return{verified:false,refundable:true,qualifies:false,reason:'missing-checkin'};if(!Array.isArray(policy?.cancelPolicyInfos))return{verified:false,refundable:true,qualifies:false,reason:'missing-policy-list'};const positive=positivePolicies(policy);if(!positive.length)return{verified:true,refundable:true,qualifies:true,freeUntil:null,reason:'no-positive-fee-policy'};const freeUntil=isoDatePart(positive[0].cancelTime),threshold=addDays(checkin,-Math.abs(Number(requiredDays)||0));return{verified:true,refundable:true,freeUntil,threshold,qualifies:!!threshold&&freeUntil>=threshold,reason:freeUntil>=threshold?'deadline-sufficient':'deadline-too-early'};}
function selectedOption(o){const opts=Array.isArray(o?.rateOptions)?o.rateOptions:[];if(!opts.length)return null;const price=Number(o?.price),board=norm(o?.board),room=norm(o?.room);return opts.find(x=>Number(x?.price)===price&&norm(x?.board)===board&&norm(x?.room)===room)||opts.find(x=>Number(x?.price)===price&&norm(x?.board)===board)||opts.find(x=>Number(x?.price)===price)||opts[0];}
function assessmentForOffer(o){const opt=selectedOption(o);let ci=o?.checkin||'';try{if(!ci&&typeof searchState!=='undefined')ci=searchState?.checkin||'';}catch(_){}return cancellationAssessment(opt?.cancellationPolicies,ci,REQUIRED_FREE_DAYS);}
function enrichOptions(item,options){const rooms=Array.isArray(item?.roomTypes)?item.roomTypes:[];return(Array.isArray(options)?options:[]).map(opt=>{const raw=rooms?.[Number(opt?.roomIndex)]?.rates?.[Number(opt?.rateIndex)],policy=raw?.cancellationPolicies;return policy?{...opt,cancellationPolicies:policy}:{...opt};});}
function installExtract(){if(extractInstalled)return false;const prior=window.extractRateOptions;if(typeof prior!=='function')return false;const wrapped=function(item){return enrichOptions(item,prior(item));};wrapped.__noreyoV892=true;window.extractRateOptions=wrapped;extractInstalled=true;return true;}
function installFilter(){if(filterInstalled)return false;const prior=window.filterAndRankOffers;if(typeof prior!=='function')return false;const wrapped=function(input){let mode='any';try{mode=window.states?.Preis2||states?.Preis2||'any';}catch(_){}if(mode!=='must')return prior(input);let stateObj=null,restore=null;try{stateObj=typeof states!=='undefined'?states:window.states;restore=stateObj?.Preis2;if(stateObj)stateObj.Preis2='wish';}catch(_){}let out;try{out=prior(input);}finally{try{if(stateObj)stateObj.Preis2=restore;}catch(_){}}return(Array.isArray(out)?out:[]).filter(o=>assessmentForOffer(o).qualifies===true);};wrapped.__noreyoV892=true;window.filterAndRankOffers=wrapped;filterInstalled=true;return true;}
function installCriteria(){if(criteriaInstalled)return false;const prior=window.detailCriteria;if(typeof prior!=='function')return false;const wrapped=function(o){const rows=prior(o);let active=false;try{active=(typeof states!=='undefined'?states?.Preis2:window.states?.Preis2)!=='any';}catch(_){}if(!active||!Array.isArray(rows))return rows;const a=assessmentForOffer(o);return rows.map(row=>{if(row?.name!=='Stornierbar')return row;if(!a.verified)return{...row,ok:null,note:'Stornierungsfrist vom Anbieter noch nicht vollständig verifizierbar',status:'Frist prüfen'};if(a.qualifies)return{...row,ok:true,note:a.freeUntil?`Kostenfreie Frist mindestens bis ${a.freeUntil}`:'Keine positive Stornogebühr in den übermittelten Policies',status:'Bestätigt'};return{...row,ok:false,note:a.freeUntil?`Kostenfreie Frist endet bereits am ${a.freeUntil}`:'Tarif nicht kostenfrei stornierbar',status:'Nicht erfüllt'};});};wrapped.__noreyoV892=true;window.detailCriteria=wrapped;criteriaInstalled=true;return true;}
function rewriteCancellationCopy(root=document){let changed=false;const walker=document.createTreeWalker(root.body||root,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes){const old=node.nodeValue||'',next=old.replace(/Kostenlos stornierbar laut Tarif/g,'Stornierbarer Tarif · genaue Frist prüfen');if(next!==old){node.nodeValue=next;changed=true;}}return changed;}
function install(){return installExtract()|installFilter()|installCriteria();}
function run(){raf=0;install();rewriteCancellationCopy();}
function schedule(){if(raf)return;raf=requestAnimationFrame(run);}
function observe(){if(observer){observer.disconnect();observer=null;}if(typeof MutationObserver==='undefined'||!document.body)return false;observer=new MutationObserver(schedule);observer.observe(document.body,{subtree:true,childList:true,characterData:true});schedule();return true;}
function cleanup(){if(observer){observer.disconnect();observer=null;}if(raf){cancelAnimationFrame(raf);raf=0;}}
observe();window.addEventListener('pagehide',cleanup,{passive:true});window.addEventListener('pageshow',observe,{passive:true});window.NOREYO_V892=Object.freeze({BUILD,REQUIRED_FREE_DAYS,norm,isoDatePart,validISO,addDays,policyInfos,positivePolicies,cancellationAssessment,selectedOption,assessmentForOffer,enrichOptions,installExtract,installFilter,installCriteria,rewriteCancellationCopy,install,run,schedule,observe,cleanup});
})();