/* NOREYO V5.96 — unified early search preflight on current main */
(function(){
'use strict';
const BUILD='5.96';
let busy=false,busyButton=null,busyTimer=0,observer=null,rootObserver=null,observedRoot=null,baseline='';
function norm(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss');}
function notify(msg){try{if(typeof showToast==='function')showToast(msg);else if(typeof window.toast==='function')window.toast(msg);}catch(_){}}
function state(){try{return typeof searchState!=='undefined'&&searchState?searchState:null;}catch(_){return null;}}
function mode(){const active=document.querySelector('#discover .product-mode.on');const t=norm(active?.textContent||'');if(t.includes('kreuzfahrt'))return'cruise';if(t.includes('hotel'))return'hotel';if(t.includes('flug'))return'flight';try{if(typeof productMode==='string'&&productMode)return productMode;}catch(_){}return'package';}
function validISO(value){const s=String(value||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;const d=new Date(s+'T12:00:00');return !Number.isNaN(d.getTime())&&d.getFullYear()===Number(s.slice(0,4))&&d.getMonth()+1===Number(s.slice(5,7))&&d.getDate()===Number(s.slice(8,10));}
function todayISO(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function destinationPresent(){try{return typeof dest!=='undefined'&&String(dest||'').trim().length>=2;}catch(_){return false;}}
function airportsValid(){const s=state(),arr=Array.isArray(s?.airports)?s.airports:[];return arr.length>=1&&arr.length<=5&&arr.every(x=>/^[A-Z]{3}$/.test(String(x||'').trim().toUpperCase()));}
function coreSearchError(){const m=mode(),s=state();if(m==='cruise')return'';if(!destinationPresent())return'Bitte zuerst ein Reiseziel auswählen.';const checkin=String(s?.checkin||''),checkout=String(s?.checkout||'');if(!validISO(checkin)||!validISO(checkout))return'Bitte einen gültigen Reisezeitraum auswählen.';if(checkin<todayISO())return'Das Abreisedatum liegt in der Vergangenheit. Bitte den Zeitraum aktualisieren.';if(checkout<=checkin)return'Das Rückreisedatum muss nach dem Abreisedatum liegen.';if((m==='package'||m==='flight')&&!airportsValid())return'Bitte mindestens einen gültigen Abflughafen auswählen.';return'';}
function validateSearchSafety(){const family=window.NOREYO_V592,provider=window.NOREYO_V594;if(!family)return{error:'Reisendenprüfung wird geladen. Bitte gleich noch einmal suchen.',planner:''};if(!provider)return{error:'Belegungsprüfung wird geladen. Bitte gleich noch einmal suchen.',planner:''};try{family.applyFamily();const fe=String(family.validateBeforeSearch?.()||'');if(fe)return{error:fe,planner:'travellers'};const oe=String(provider.occupancyError?.()||'');if(oe)return{error:oe,planner:'travellers'};const ce=coreSearchError();if(ce){const t=norm(ce),planner=t.includes('reiseziel')?'destination':t.includes('abflughafen')?'airports':(t.includes('zeitraum')||t.includes('abreise')||t.includes('rueckreise'))?'dates':'';return{error:ce,planner};}return{error:'',planner:''};}catch(_){return{error:'Suchprüfung konnte nicht abgeschlossen werden. Bitte erneut versuchen.',planner:''};}}
function openPlannerFor(kind){try{if(typeof openPlanner==='function'){openPlanner(kind);return;}}catch(_){}const map={destination:['.destInput','.destinationInput','[data-field="destination"]'],dates:['.dateInput','[data-field="dates"]'],airports:['.airportInput','[data-field="airports"]'],travellers:['.travellerInput','.travelerInput','[data-field="travellers"]']};for(const q of map[kind]||[]){const el=document.querySelector(q);if(el){el.click();return;}}}
function resultRoot(){return document.getElementById('results');}
function signature(){const offers=[...document.querySelectorAll('#offers .offer')];return offers.length+':'+offers.slice(0,3).map(x=>String(x.textContent||'').replace(/\s+/g,' ').slice(0,180)).join('|');}
function terminal(){const t=norm(resultRoot()?.textContent||'');return /keine (?:angebote|hotels|fluege|reisen|ergebnisse)|nichts gefunden|suche fehlgeschlagen|fehler bei der suche|erneut versuchen/.test(t);}
function releaseBusy(){if(!busy)return;busy=false;clearTimeout(busyTimer);busyTimer=0;if(busyButton){busyButton.disabled=false;busyButton.removeAttribute('aria-disabled');}busyButton=null;resultRoot()?.setAttribute('aria-busy','false');}
function beginBusy(btn){busy=true;baseline=signature();busyButton=btn||null;if(btn){btn.disabled=true;btn.setAttribute('aria-disabled','true');}resultRoot()?.setAttribute('aria-busy','true');clearTimeout(busyTimer);busyTimer=setTimeout(releaseBusy,15000);}
function bindResults(){const r=resultRoot();if(!r||r===observedRoot)return;if(observer)observer.disconnect();observedRoot=r;r.setAttribute('aria-live','polite');r.setAttribute('aria-busy',busy?'true':'false');observer=new MutationObserver(()=>{if(busy&&(signature()!==baseline||terminal()))releaseBusy();});observer.observe(r,{childList:true,subtree:true,characterData:true});}
function onClick(e){if(!(e.target instanceof Element))return;const btn=e.target.closest('.noreyo-v541-booking-cta,.liveSearchButton');if(!btn)return;const check=validateSearchSafety();if(check.error){e.preventDefault();e.stopImmediatePropagation();notify(check.error);if(check.planner)setTimeout(()=>openPlannerFor(check.planner),0);return;}if(busy){e.preventDefault();e.stopImmediatePropagation();return;}beginBusy(btn);}
function attachRoot(){if(rootObserver||typeof MutationObserver==='undefined'||!document.body)return;rootObserver=new MutationObserver(()=>{const r=resultRoot();if(r!==observedRoot){observedRoot=null;bindResults();}});rootObserver.observe(document.body,{childList:true,subtree:true});}
function cleanup(){releaseBusy();if(observer){observer.disconnect();observer=null;}if(rootObserver){rootObserver.disconnect();rootObserver=null;}observedRoot=null;}
function install(){bindResults();attachRoot();window.addEventListener('click',onClick,true);window.addEventListener('pagehide',cleanup,{passive:true});window.addEventListener('pageshow',()=>{releaseBusy();bindResults();attachRoot();},{passive:true});}
window.NOREYO_V596=Object.freeze({BUILD,validateSearchSafety,coreSearchError,validISO,airportsValid,releaseBusy,get busy(){return busy;}});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();