/* NOREYO V6.70 — async-safe favorite migration + cruise/profile lifecycle. */
(function(){
'use strict';
const BUILD='6.70';
const LEGACY_FAV_KEY='noreyoLegacyFavoriteIds584';
const LEGACY_SEED_KEY='noreyoLegacyFavoriteIdsSeeded584';
const LEGACY_SNAPSHOT_SEED_KEY='noreyoLegacyFavoriteSnapshotsSeeded589';
const LEGACY_TOMBSTONE_KEY='noreyoLegacyFavoriteTombstones589';
let syncingCruise=false,searchCardBaselineNode=null,suppressFavoriteKey='';
const pendingTimers=new Set();
function schedule(fn,delay=0){const id=setTimeout(()=>{pendingTimers.delete(id);try{fn();}catch(_){ }},delay);pendingTimers.add(id);return id;}
function clearScheduled(){pendingTimers.forEach(clearTimeout);pendingTimers.clear();}
function afterResult(result,after,args=[],ctx=null){if(result&&typeof result.then==='function')return result.then(value=>{after.apply(ctx,args);return value;});after.apply(ctx,args);return result;}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function decodeKey(v){try{return decodeURIComponent(String(v||''));}catch(_){return String(v||'');}}
function mode(){const active=document.querySelector('.view.active .product-mode.on')||document.querySelector('#discover .product-mode.on');const t=String(active?.textContent||'').toLowerCase();if(t.includes('kreuzfahrt'))return'cruise';if(t.includes('hotel'))return'hotel';if(t.includes('flug'))return'flight';try{if(typeof productMode==='string')return productMode;}catch(_){ }return'package';}
function legacyStorageKeys(){return['oneTripV52','oneTripV51','oneTripV5'];}
function storedObjects(){const out=[];legacyStorageKeys().forEach(k=>{try{const x=JSON.parse(localStorage.getItem(k)||'null');if(x&&typeof x==='object')out.push({storageKey:k,value:x});}catch(_){ }});return out;}
function tombstones(){const out=new Set();try{JSON.parse(localStorage.getItem(LEGACY_TOMBSTONE_KEY)||'[]').forEach(x=>out.add(String(x)));}catch(_){ }return out;}
function persistTombstones(set){try{localStorage.setItem(LEGACY_TOMBSTONE_KEY,JSON.stringify([...set]));}catch(_){ }}
function rememberLegacyFavoriteIds(){const ids=new Set();try{JSON.parse(localStorage.getItem(LEGACY_FAV_KEY)||'[]').forEach(x=>ids.add(String(x)));}catch(_){ }let seeded=false;try{seeded=localStorage.getItem(LEGACY_SEED_KEY)==='1';}catch(_){ }if(!seeded){try{if(typeof favs!=='undefined'&&favs&&typeof favs.forEach==='function')favs.forEach(x=>ids.add(String(x)));}catch(_){ }storedObjects().forEach(({value:x})=>{if(Array.isArray(x.favs))x.favs.forEach(id=>ids.add(String(id)));});try{localStorage.setItem(LEGACY_SEED_KEY,'1');}catch(_){ }}try{localStorage.setItem(LEGACY_FAV_KEY,JSON.stringify([...ids]));}catch(_){ }return ids;}
function persistLegacyFavoriteIds(ids){try{localStorage.setItem(LEGACY_FAV_KEY,JSON.stringify([...ids]));}catch(_){ }}
function seedLegacySnapshotsOnce(){let seeded=false;try{seeded=localStorage.getItem(LEGACY_SNAPSHOT_SEED_KEY)==='1';}catch(_){ }if(seeded)return false;let changed=false;try{if(typeof savedFavorites==='undefined'||!Array.isArray(savedFavorites))return false;const dead=tombstones(),known=new Set(savedFavorites.map(x=>String(x?.key||'')).filter(Boolean));storedObjects().forEach(({value:x})=>{if(!Array.isArray(x.savedFavorites))return;x.savedFavorites.forEach(o=>{const key=String(o?.key||'');if(key&&!dead.has(key)&&!known.has(key)){savedFavorites.push(o);known.add(key);changed=true;}});});localStorage.setItem(LEGACY_SNAPSHOT_SEED_KEY,'1');if(changed&&typeof persistState==='function')persistState();}catch(e){console.warn('NOREYO '+BUILD+' legacy favorite seed',e);}return changed;}
function scrubLegacySnapshotKey(key){key=String(key||'');if(!key)return;const dead=tombstones();dead.add(key);persistTombstones(dead);storedObjects().forEach(({storageKey,value:x})=>{if(!Array.isArray(x.savedFavorites))return;const next=x.savedFavorites.filter(o=>String(o?.key||'')!==key);if(next.length===x.savedFavorites.length)return;x.savedFavorites=next;try{localStorage.setItem(storageKey,JSON.stringify(x));}catch(_){ }});}
function recoverFavoriteSnapshots(){let changed=false,legacyChanged=false;try{if(typeof savedFavorites==='undefined'||!Array.isArray(savedFavorites))return false;seedLegacySnapshotsOnce();const known=new Set(savedFavorites.map(x=>String(x?.key||'')).filter(Boolean)),dead=tombstones(),legacy=rememberLegacyFavoriteIds();if(legacy.size&&typeof offers!=='undefined'&&Array.isArray(offers)&&typeof snapshotOffer==='function'){offers.forEach(o=>{const id=String(o?.id||'');if(!id||!legacy.has(id))return;const snap=snapshotOffer(o),key=String(snap?.key||'');if(!key)return;if(dead.has(key)||(suppressFavoriteKey&&key===suppressFavoriteKey)||known.has(key)){legacy.delete(id);legacyChanged=true;return;}savedFavorites.unshift(snap);known.add(key);changed=true;legacy.delete(id);legacyChanged=true;});}if(legacyChanged)persistLegacyFavoriteIds(legacy);if(changed&&typeof persistState==='function')persistState();}catch(e){console.warn('NOREYO '+BUILD+' favorite recovery',e);}return changed;}
function fallbackFavorites(){try{const list=document.getElementById('favList'),empty=document.getElementById('favEmpty');if(!list||!empty||typeof savedFavorites==='undefined'||!Array.isArray(savedFavorites)||!savedFavorites.length||list.children.length)return;empty.style.display='none';list.innerHTML=savedFavorites.map(o=>{const key=encodeURIComponent(String(o?.key||''));let src='';try{src=typeof safeImageUrl==='function'?safeImageUrl(o?.img):String(o?.img||'');}catch(_){src=String(o?.img||'');}const hotel=esc(o?.hotel||'Gespeichertes Hotel'),region=esc(String(o?.region||o?.destination||'Reise').toUpperCase()),stars=Math.max(0,Number(o?.stars)||0),price=Number(o?.price)||0;return '<article class="v584-fav-card" data-v584-open="'+key+'">'+(src?'<img src="'+esc(src)+'" alt="'+hotel+'">':'')+'<div><small>'+region+(stars?' · '+stars+' STERNE':'')+'</small><b>'+hotel+'</b><span>'+(price?price.toLocaleString('de-DE')+' €':'Gespeichertes Angebot')+'</span></div><button type="button" data-v584-remove="'+key+'" aria-label="Favorit entfernen">×</button></article>';}).join('');list.querySelectorAll('[data-v584-open]').forEach(card=>card.addEventListener('click',e=>{if(e.target.closest('[data-v584-remove]'))return;try{if(typeof showSavedDetail==='function')showSavedDetail(decodeKey(card.dataset.v584Open),'favorites');}catch(_){ }}));list.querySelectorAll('[data-v584-remove]').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();try{if(typeof removeFavorite==='function')removeFavorite(decodeKey(btn.dataset.v584Remove));}catch(_){ }}));}catch(e){console.warn('NOREYO '+BUILD+' favorite fallback',e);}}
function refreshFavorites(){recoverFavoriteSnapshots();try{if(typeof renderFavs==='function'){const r=renderFavs();if(r&&typeof r.then==='function')return r.then(value=>{fallbackFavorites();return value;});}}catch(e){console.warn('NOREYO '+BUILD+' render favorites',e);}fallbackFavorites();}
function afterFunction(name,after){try{const original=eval(name);if(typeof original!=='function'||original.__noreyoV584)return;const wrapped=function(){const args=[...arguments],ctx=this,r=original.apply(ctx,args);return afterResult(r,after,args,ctx);};wrapped.__noreyoV584=true;eval(name+'=wrapped');}catch(_){ }}
function wrapRemoveFavorite(){try{const original=removeFavorite;if(typeof original!=='function'||original.__noreyoV584Remove)return;const wrapped=function(key){suppressFavoriteKey=String(key||'');scrubLegacySnapshotKey(suppressFavoriteKey);let r;try{r=original.apply(this,arguments);}catch(error){suppressFavoriteKey='';throw error;}if(r&&typeof r.then==='function')return r.then(value=>{refreshFavorites();suppressFavoriteKey='';return value;},error=>{suppressFavoriteKey='';throw error;});try{refreshFavorites();return r;}finally{suppressFavoriteKey='';}};wrapped.__noreyoV584Remove=true;removeFavorite=wrapped;}catch(_){ }}
function enhanceCruiseCard(card){if(!card)return;const head=card.querySelector('.noreyo-v552-search-head b');if(head)head.textContent='Route, Zeitraum, Reisende & Kabine';const cta=card.querySelector('[data-cruise-search]');if(cta){const first=cta.querySelector('span');if(first)first.textContent='Kreuzfahrt planen';}if(!card.querySelector('.noreyo-v584-cruise-note')){const grid=card.querySelector('.noreyo-v552-cruise-grid');if(grid)grid.insertAdjacentHTML('afterend','<p class="noreyo-v584-cruise-note">Kreuzfahrt-Suche ist vorbereitet. Live-Angebote werden mit der Kreuzfahrt-Anbieteranbindung aktiviert.</p>');}}
function bindCruiseMirror(card){card.querySelectorAll('[data-cruise-picker]').forEach(btn=>{if(btn.dataset.v584Bound==='1')return;btn.dataset.v584Bound='1';btn.addEventListener('click',()=>{const kind=btn.dataset.cruisePicker,source=document.querySelector('#discover [data-cruise-picker="'+kind+'"]');if(source&&source!==btn)source.click();});});const cta=card.querySelector('[data-cruise-search]');if(cta&&cta.dataset.v584Bound!=='1'){cta.dataset.v584Bound='1';cta.addEventListener('click',()=>{const source=document.querySelector('#discover [data-cruise-search]');if(source&&source!==cta)source.click();});}}
function restoreSearchView(refresh=true){const mirror=document.querySelector('#searchView .noreyo-v584-cruise-mirror');if(!mirror||!searchCardBaselineNode)return false;mirror.replaceWith(searchCardBaselineNode);const restored=searchCardBaselineNode;searchCardBaselineNode=null;if(refresh)try{if(typeof updateSearchUI==='function')updateSearchUI();}catch(_){ }return !!restored;}
function syncCruiseSearchView(){if(syncingCruise||mode()!=='cruise')return;const source=document.querySelector('#discover .search-card.noreyo-v552-cruise-search');let target=document.querySelector('#searchView .search-card');if(!source||!target)return;syncingCruise=true;try{enhanceCruiseCard(source);if(!target.classList.contains('noreyo-v584-cruise-mirror')){if(!searchCardBaselineNode)searchCardBaselineNode=target;const mirror=source.cloneNode(true);mirror.className='search-card noreyo-v552-cruise-search noreyo-v584-cruise-mirror';target.replaceWith(mirror);target=mirror;}else target.innerHTML=source.innerHTML;enhanceCruiseCard(target);bindCruiseMirror(target);}finally{syncingCruise=false;}}
function syncCruiseValues(){if(mode()==='cruise')syncCruiseSearchView();else restoreSearchView();}
try{if(typeof openFilter==='function'&&!openFilter.__noreyoV584CruiseGuard){const priorOpenFilter=openFilter,guarded=function(){if(mode()==='cruise'){try{if(typeof showToast==='function')showToast('Kabine und Kreuzfahrt-Wünsche stellst du direkt in der Kreuzfahrt-Suche ein.');}catch(_){ }return;}return priorOpenFilter.apply(this,arguments);};guarded.__noreyoV584CruiseGuard=true;openFilter=guarded;}}catch(_){ }
try{if(typeof setProductMode==='function'&&!setProductMode.__noreyoV584){const priorSetProductMode=setProductMode,wrapped=function(next){const args=[...arguments],ctx=this,r=priorSetProductMode.apply(ctx,args);return afterResult(r,()=>schedule(()=>{if(next==='cruise'||mode()==='cruise')syncCruiseSearchView();else restoreSearchView();}),[],ctx);};wrapped.__noreyoV584=true;setProductMode=wrapped;}}catch(_){ }
try{if(typeof updateSearchUI==='function'&&!updateSearchUI.__noreyoV584){const priorUpdate=updateSearchUI,wrapped=function(){const args=[...arguments],ctx=this,r=priorUpdate.apply(ctx,args);return afterResult(r,()=>schedule(syncCruiseValues),args,ctx);};wrapped.__noreyoV584=true;updateSearchUI=wrapped;}}catch(_){ }
afterFunction('renderOffers',recoverFavoriteSnapshots);afterFunction('toggleFav',refreshFavorites);afterFunction('toggleSnapshotFavorite',refreshFavorites);wrapRemoveFavorite();
try{if(typeof go==='function'&&!go.__noreyoV584){const priorGo=go,wrapped=function(view){const args=[...arguments],ctx=this,r=priorGo.apply(ctx,args);return afterResult(r,()=>{if(view==='favorites')refreshFavorites();if(view==='profile')polishProfile();if(view==='searchView')schedule(()=>{if(mode()==='cruise')syncCruiseSearchView();else restoreSearchView();});},args,ctx);};wrapped.__noreyoV584=true;go=wrapped;}}catch(_){ }
function polishProfile(){const root=document.getElementById('profile');if(!root)return;const kicker=root.querySelector('.simple-intro .kicker');if(kicker)kicker.textContent='DEIN NOREYO';const h=root.querySelector('.simple-intro h1');if(h)h.textContent='Was soll NOREYO sich für dich merken?';[...root.querySelectorAll('.menu-row')].forEach(row=>{const b=row.querySelector('b'),s=row.querySelector('small'),t=(b?.textContent||'').trim();if(t==='Standard-Präferenzen'){b.textContent='Meine Urlaubswünsche';if(s)s.textContent='Balkon, Lage, Verpflegung, Hotel & mehr';}else if(t==='Preisbeobachtung'){b.textContent='Preisalarm';if(s&&s.textContent==='Keine aktive Beobachtung')s.textContent='Noch kein Preisalarm aktiv';}else if(t==='Treueprogramme')row.hidden=true;});}
function cleanup(){clearScheduled();syncingCruise=false;suppressFavoriteKey='';restoreSearchView(false);}
function restore(){polishProfile();recoverFavoriteSnapshots();if(mode()==='cruise')schedule(syncCruiseSearchView);}
document.addEventListener('click',e=>{if(e.target.closest?.('[data-cruise-value],[data-close-cruise-sheet]'))schedule(syncCruiseSearchView);if(e.target.closest?.('.nav-btn[data-view="favorites"]'))schedule(refreshFavorites);},false);
window.addEventListener('pagehide',cleanup,{passive:true});window.addEventListener('pageshow',restore,{passive:true});
rememberLegacyFavoriteIds();seedLegacySnapshotsOnce();recoverFavoriteSnapshots();polishProfile();if(mode()==='cruise')schedule(syncCruiseSearchView);
window.NOREYO_V584=Object.freeze({refreshFavorites,recoverFavoriteSnapshots,syncCruiseSearchView,restoreSearchView,decodeKey,scrubLegacySnapshotKey,afterResult,clearScheduled,version:BUILD,get pendingTimerCount(){return pendingTimers.size;}});
})();