/* NOREYO V11.58 — checkout authentication boundary.
   Adds a session-only Supabase Auth magic-link flow before any future BOOK step.
   The public anon key may be used client-side; no service-role/provider secret is exposed.
   Auth tokens live in sessionStorage only and are validated against /auth/v1/user. */
(function(){
'use strict';
const BUILD='11.58';
const PROJECT_URL='https://fcvffslhnaqlwitaeers.supabase.co';
const STORAGE_KEY='noreyo_auth_session_v1';
let observer=null,raf=0,bound=false,validating=null;
function anon(){try{return typeof anonKey!=='undefined'?String(anonKey||''):'';}catch(_){return'';}}
function session(){try{const raw=sessionStorage.getItem(STORAGE_KEY);if(!raw)return null;const s=JSON.parse(raw);return s&&s.access_token?s:null;}catch(_){return null;}}
function save(s){if(!s?.access_token)return false;const out={access_token:String(s.access_token),expires_at:Number(s.expires_at)||0,user_id:String(s.user?.id||s.user_id||''),email:String(s.user?.email||s.email||'')};try{sessionStorage.setItem(STORAGE_KEY,JSON.stringify(out));return true;}catch(_){return false;}}
function clear(){try{sessionStorage.removeItem(STORAGE_KEY);}catch(_){}return true;}
function safeEmail(v){const s=String(v||'').trim().toLowerCase();return /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(s)?s:'';}
function redirectTo(){return `${location.origin}${location.pathname}${location.search||''}`;}
function stripAuthHash(){try{if(!location.hash)return false;const p=new URLSearchParams(location.hash.slice(1));if(!p.has('access_token')&&!p.has('error'))return false;history.replaceState(null,'',`${location.pathname}${location.search||''}`);return true;}catch(_){return false;}}
function ingestHash(){try{const h=String(location.hash||'');if(!h.startsWith('#'))return false;const p=new URLSearchParams(h.slice(1));const token=p.get('access_token');if(!token)return false;const expiresIn=Math.max(60,Number(p.get('expires_in'))||3600);const ok=save({access_token:token,expires_at:Math.floor(Date.now()/1000)+expiresIn});stripAuthHash();return ok;}catch(_){return false;}}
async function user(s=session()){if(!s?.access_token)return null;const key=anon();if(!key)return null;if(validating)return validating;validating=(async()=>{try{const r=await fetch(`${PROJECT_URL}/auth/v1/user`,{headers:{apikey:key,Authorization:`Bearer ${s.access_token}`}});if(!r.ok){clear();return null;}const u=await r.json();save({...s,user:u});return u;}catch(_){return null;}finally{validating=null;}})();return validating;}
async function sendMagicLink(email){const mail=safeEmail(email);if(!mail)throw new Error('Bitte gib eine gültige E-Mail-Adresse ein.');const key=anon();if(!key)throw new Error('Die sichere Anmeldung konnte nicht initialisiert werden.');const r=await fetch(`${PROJECT_URL}/auth/v1/otp`,{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify({email:mail,create_user:true,email_redirect_to:redirectTo()})});let payload={};try{payload=await r.json();}catch(_){}if(!r.ok)throw new Error(String(payload?.msg||payload?.message||'Anmeldelink konnte nicht gesendet werden.'));return true;}
function authenticated(){const s=session();return !!s?.access_token&&(!s.expires_at||s.expires_at>Math.floor(Date.now()/1000)+30);}
function host(){return document.querySelector('.noreyo-v1146-booking-data');}
function ensure(){const root=host();if(!root)return false;let box=root.querySelector('.noreyo-v1158-auth');if(box)return box;box=document.createElement('section');box.className='noreyo-v1158-auth';box.innerHTML='<h4>Sichere Anmeldung vor der Buchung</h4><p class="noreyo-v1158-copy">Vor einem späteren BOOK-Schritt muss die E-Mail-Adresse authentifiziert sein.</p><div class="noreyo-v1158-row"><input class="noreyo-v1158-email" type="email" autocomplete="email" inputmode="email" placeholder="E-Mail-Adresse" aria-label="E-Mail-Adresse für sichere Anmeldung"><button type="button" class="noreyo-v1158-send">Anmeldelink senden</button></div><div class="noreyo-v1158-status" role="status" aria-live="polite" aria-atomic="true"></div>';root.prepend(box);return box;}
function setPreparedAccess(enabled){const root=host();if(!root)return false;const btn=root.querySelector('.noreyo-v1146-prepare');if(!btn)return false;const disabled=!enabled;if(btn.disabled===disabled&&btn.getAttribute('aria-disabled')===String(disabled))return false;btn.disabled=disabled;btn.setAttribute('aria-disabled',String(disabled));return true;}
async function render(){raf=0;const box=ensure();if(!box||box===false)return false;const status=box.querySelector('.noreyo-v1158-status'),row=box.querySelector('.noreyo-v1158-row');let ok=false,u=null;if(authenticated())u=await user();ok=!!u;setPreparedAccess(ok);if(row)row.hidden=ok;if(status)status.textContent=ok?`Angemeldet${u?.email?` als ${u.email}`:''}. Buchungsdaten können jetzt vorbereitet werden.`:'Noch nicht angemeldet. Sende dir einen sicheren Einmal-Link per E-Mail.';return ok;}
async function onClick(e){const btn=e.target?.closest?.('.noreyo-v1158-send');if(!btn)return;e.preventDefault();e.stopPropagation();const box=btn.closest('.noreyo-v1158-auth');if(!box)return;const input=box.querySelector('.noreyo-v1158-email'),status=box.querySelector('.noreyo-v1158-status');btn.disabled=true;btn.textContent='Link wird gesendet …';try{await sendMagicLink(input?.value||'');if(status)status.textContent='Anmeldelink gesendet. Öffne ihn auf diesem Gerät und kehre zu NOREYO zurück.';}catch(err){if(status)status.textContent=String(err?.message||err||'Anmeldung fehlgeschlagen.');}finally{btn.disabled=false;btn.textContent='Anmeldelink senden';}}
function schedule(){if(!raf)raf=requestAnimationFrame(()=>{render().catch(()=>{});});}
function install(){ingestHash();if(bound)return false;bound=true;if(typeof MutationObserver!=='undefined'&&document.body){observer=new MutationObserver(schedule);observer.observe(document.body,{subtree:true,childList:true});}document.addEventListener('click',onClick,true);schedule();return true;}
function cleanup(){if(observer){observer.disconnect();observer=null;}if(bound){document.removeEventListener('click',onClick,true);bound=false;}if(raf){cancelAnimationFrame(raf);raf=0;}}
install();window.addEventListener('pagehide',cleanup,{passive:true});window.addEventListener('pageshow',install,{passive:true});
window.NOREYO_V1158=Object.freeze({BUILD,PROJECT_URL,STORAGE_KEY,anon,session,save,clear,safeEmail,redirectTo,stripAuthHash,ingestHash,user,sendMagicLink,authenticated,host,ensure,setPreparedAccess,render,onClick,schedule,install,cleanup});
})();