(function(){
  const checks=[
    ['Zimmer0','Balkon',o=>o.confirmed?.balcony===true],['Zimmer1','Meerblick',o=>o.confirmed?.seaView===true],['Zimmer2','Terrasse',o=>o.confirmed?.terrace===true],['Hotel0','4★+',o=>Number(o.stars||0)>=4],['Hotel4','Spa',o=>o.confirmed?.spa===true],['Hotel5','Fitness',o=>o.confirmed?.fitness===true],['Hotel6','Frühstück',o=>o.confirmed?.breakfast===true],['Hotel7','All Inclusive',o=>o.confirmed?.allInclusive===true],['Preis2','Stornierbar',o=>o.refundable===true]
  ];
  function matchData(o){let earned=0,total=0;const items=[];for(const [key,label,test] of checks){const state=states[key]||'any';if(state==='any')continue;const ok=!!test(o),w=state==='must'?3:1;total+=w;if(ok)earned+=w;items.push({label,state,ok})}if(mealPlanFilter&&mealPlanFilter!=='ANY'){total+=2;earned+=2;items.push({label:mealPlanLabel(),state:'must',ok:true})}return {percent:total?Math.round(earned/total*100):null,items}}
  function decorate(){document.querySelectorAll('#offers .offer').forEach((card,i)=>{const o=offers[i];if(!o)return;const m=matchData(o);card.classList.add('noreyo-offer');const img=card.querySelector('.offer-img');if(img&&!img.querySelector('.noreyo-match-badge'))img.insertAdjacentHTML('beforeend',`<div class="noreyo-match-badge"><span>NOREYO MATCH</span><strong>${m.percent===null?'LIVE':m.percent+'%'}</strong><small>${m.items.length?m.items.filter(x=>x.ok).length+' von '+m.items.length+' prüfbaren Kriterien bestätigt':'Live-Daten geprüft'}</small></div>`);const line=card.querySelector('.offer-matchline');if(line){const ok=m.items.filter(x=>x.ok).slice(0,3),open=m.items.filter(x=>!x.ok&&x.state==='wish').length;line.innerHTML=ok.map(x=>`<span class="offer-matchchip ${x.state}">${x.state==='must'?'Pflicht':'Wunsch'} · ${safeText(x.label)}</span>`).join('')+(open?`<span class="offer-matchchip neutral">${open} ${open===1?'Wunsch':'Wünsche'} offen</span>`:'')||'<span class="offer-matchchip neutral">Live-Tarif geprüft</span>'}const e=card.querySelector('.offer-essentials');if(e)e.classList.add('noreyo-essentials');const p=card.querySelector('.offer-price-context');if(p)p.classList.add('noreyo-price-panel');const btn=card.querySelector('.dark-btn');if(btn){btn.classList.add('noreyo-cta');btn.innerHTML=`Hotel & Tarife ansehen ${svg('chev')}`;if(!card.querySelector('.noreyo-trust-row'))btn.insertAdjacentHTML('beforebegin',`<div class="noreyo-trust-row"><span><i></i>${o.live===true?'Preis & Verfügbarkeit gerade live geprüft':'Gespeicherter Stand'}</span><span>${o.refundable?'Stornierbar':'Tarifbedingungen'}</span></div>`)}})}
  const baseRender=renderOffers;renderOffers=function(){baseRender();decorate()};
  const baseFilter=filterAndRankOffers;filterAndRankOffers=function(input){const out=baseFilter(input);out.sort((a,b)=>(matchData(b).percent??-1)-(matchData(a).percent??-1)||Number(String(b.rating||0).replace(',','.'))-Number(String(a.rating||0).replace(',','.'))||Number(a.price||Infinity)-Number(b.price||Infinity));return out};
  decorate();
})();
