/* NOREYO V11.46 — session-only hotel booking-data preparation.
   Current hotel search uses one occupancy, so LiteAPI requires one primary guest
   with occupancyNumber=1 plus a holder. Collect/validate those details only after
   the authoritative PREBOOK gate is ready. Do not persist PII and do not BOOK. */
(function(){
'use strict';
const BUILD='11.46';
let observer=null,raf=0,bound=false;
function snap(){return window.NOREYO_HOTEL_PREBOOK||null;}
function ready(){try{return !!window.NOREYO_V1128?.checkoutReady?.()&&!!window.NOREYO_V1142?.complete?.();}catch(_){return false;}}
function sessionKey(){const s=snap();if(!s)return'';return [String(s.prebookId||''),String(s.offerId||''),String(s.price??''),String(s.currency||'')].join('|');}
function prepared(){return window.NOREYO_HOTEL_BOOKING_DRAFT||null;}
function clear(){if(!prepared())return false;try{delete window.NOREYO_HOTEL_BOOKING_DRAFT;}catch(_){window.NOREYO_HOTEL_BOOKING_DRAFT=undefined;}return true;}
function text(v,max=120){return String(v||'').replace(/[\u0000-\u001f\u007f]/g,' ').trim().replace(/\s+/g,' ').slice(0,max);}
function email(v){const s=text(v,200).toLowerCase();return /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(s)?s:'';}
function phone(v){const s=text(v,40);return !s||/^\+?[0-9][0-9 ()/.-]{5,39}$/.test(s)?s:'';}
function validate(raw){const firstName=text(raw?.firstName,80),lastName=text(raw?.lastName,100),mail=email(raw?.email),rawPhone=text(raw?.phone,40),tel=phone(rawPhone);const errors=[];if(firstName.length<2)errors.push('Bitte gib den Vornamen des Hauptgasts ein.');if(lastName.length<2)errors.push('Bitte gib den Nachnamen des Hauptgasts ein.');if(!mail)errors.push('Bitte gib eine gültige E-Mail-Adresse ein.');if(rawPhone&&!tel)errors.push('Bitte prüfe die Telefonnummer.');return{ok:errors.length===0,errors,data:{firstName,lastName,email:mail,phone:tel}};}
function payload(data){const s=snap();if(!s||!ready())return null;const v=validate(data);if(!v.ok)return null;const holder={firstName:v.data.firstName,lastName:v.data.lastName,email:v.data.email};if(v.data.phone)holder.phone=v.data.phone;return Object.freeze({sessionKey:sessionKey(),prebookId:String(s.prebookId),holder:Object.freeze(holder),guests:Object.freeze([Object.freeze({occupancyNumber:1,firstName:v.data.firstName,lastName:v.data.lastName,email:v.data.email})]),preparedAt:new Date().toISOString()});}
function owned(d=prepared()){return !!d&&!!sessionKey()&&d.sessionKey===sessionKey()&&ready();}
function host(){return document.querySelector('.noreyo-v1128-ready');}
function ensure(){const box=host();if(!box||!ready()){if(prepared())clear();const old=document.querySelector('.noreyo-v1146-booking-data');if(old)old.remove();return false;}let section=document.querySelector('.noreyo-v1146-booking-data');if(section)return section;section=document.createElement('section');section.className='noreyo-v1146-booking-data';section.innerHTML='<h3>Buchungsdaten vorbereiten</h3><p>Diese Angaben bleiben nur in dieser geöffneten Sitzung. Es wird noch nichts gebucht oder bezahlt.</p><div class="noreyo-v1146-grid"><label>Vorname<input class="noreyo-v1146-first" autocomplete="given-name" inputmode="text" maxlength="80"></label><label>Nachname<input class="noreyo-v1146-last" autocomplete="family-name" inputmode="text" maxlength="100"></label><label>E-Mail<input class="noreyo-v1146-email" type="email" autocomplete="email" inputmode="email" maxlength="200"></label><label>Telefon <small>(optional)</small><input class="noreyo-v1146-phone" type="tel" autocomplete="tel" inputmode="tel" maxlength="40"></label></div><div class="noreyo-v1146-feedback" role="status" aria-live="polite" aria-atomic="true"></div><button type="button" class="dark-btn noreyo-v1146-prepare">Buchungsdaten prüfen</button>';box.appendChild(section);return section;}
function values(section){return{firstName:section.querySelector('.noreyo-v1146-first')?.value||'',lastName:section.querySelector('.noreyo-v1146-last')?.value||'',email:section.querySelector('.noreyo-v1146-email')?.value||'',phone:section.querySelector('.noreyo-v1146-phone')?.value||''};}
function render(){raf=0;if(prepared()&&!owned())clear();const section=ensure();if(!section||section===false)return false;const feedback=section.querySelector('.noreyo-v1146-feedback'),btn=section.querySelector('.noreyo-v1146-prepare');if(owned()){if(feedback)feedback.textContent='Buchungsdaten geprüft und für diese Checkout-Session vorbereitet.';if(btn)btn.textContent='Buchungsdaten erneut prüfen';}return true;}
function onInput(e){if(e.target?.closest?.('.noreyo-v1146-booking-data')&&prepared())clear();}
function onClick(e){const btn=e.target?.closest?.('.noreyo-v1146-prepare');if(!btn)return;e.preventDefault();e.stopPropagation();const section=btn.closest('.noreyo-v1146-booking-data');if(!section)return;const result=validate(values(section)),feedback=section.querySelector('.noreyo-v1146-feedback');if(!result.ok){clear();if(feedback)feedback.textContent=result.errors[0];return;}const draft=payload(result.data);if(!draft){clear();if(feedback)feedback.textContent='Die Checkout-Session ist nicht mehr buchungsbereit. Bitte Tarifdaten erneut bestätigen.';return;}window.NOREYO_HOTEL_BOOKING_DRAFT=draft;if(feedback)feedback.textContent='Buchungsdaten geprüft und für diese Checkout-Session vorbereitet.';btn.textContent='Buchungsdaten erneut prüfen';}
function schedule(){if(!raf)raf=requestAnimationFrame(render);}
function install(){if(bound)return false;bound=true;if(typeof MutationObserver!=='undefined'&&document.body){observer=new MutationObserver(schedule);observer.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['data-checkout-ready']});}document.addEventListener('click',onClick,true);document.addEventListener('input',onInput,true);schedule();return true;}
function cleanup(){if(observer){observer.disconnect();observer=null;}if(bound){document.removeEventListener('click',onClick,true);document.removeEventListener('input',onInput,true);bound=false;}if(raf){cancelAnimationFrame(raf);raf=0;}clear();}
install();window.addEventListener('pagehide',cleanup,{passive:true});window.addEventListener('pageshow',install,{passive:true});window.NOREYO_V1146=Object.freeze({BUILD,snap,ready,sessionKey,prepared,clear,text,email,phone,validate,payload,owned,host,ensure,values,render,onInput,onClick,schedule,install,cleanup});
})();