/* NOREYO V10.14 — complete saved-detail read-only truth.
   Saved favorite/trip snapshots are historical. Force them non-live, keep re-renders
   historical, remove stale live-rate wording and make historical rate choices read-only. */
(function(){
'use strict';
const BUILD='10.14';
let priorShow=null,priorRender=null,priorShowDetail=null,installed=false,observer=null,raf=0,activeSavedKey='';
function snapshotByEncoded(encoded){try{return typeof snapshotByKey==='function'?snapshotByKey(encoded):null;}catch(_){return null;}}
function savedClone(o,source){if(!o)return null;return {...o,live:false,savedSnapshot:true,savedSource:String(source||'favorites'),savedPrice:Number(o.price)};}
function keyOf(o){return String(o?.key||'');}
function install(){if(installed||typeof window.showSavedDetail!=='function')return false;priorShow=window.showSavedDetail;priorRender=typeof window.renderDetail==='function'?window.renderDetail:null;priorShowDetail=typeof window.showDetail==='function'?window.showDetail:null;window.showSavedDetail=function(encoded,source='favorites'){const o=snapshotByEncoded(encoded);if(!o)return priorShow.apply(this,arguments);activeSavedKey=keyOf(o);const safe=savedClone(o,source);if(typeof openDetailSnapshot==='function')return openDetailSnapshot(safe,source);return priorShow.apply(this,arguments);};window.showSavedDetail.__noreyoV1014=true;if(priorRender){window.renderDetail=function(o,...args){const next=activeSavedKey&&keyOf(o)===activeSavedKey?savedClone(o,o?.savedSource||'saved'):o;const result=priorRender.call(this,next,...args);if(activeSavedKey)setTimeout(schedule,0);return result;};window.renderDetail.__noreyoV1014=true;}if(priorShowDetail){window.showDetail=function(...args){activeSavedKey='';return priorShowDetail.apply(this,args);};window.showDetail.__noreyoV1014=true;}installed=true;return true;}
function restore(){if(!installed)return false;if(priorShow)window.showSavedDetail=priorShow;if(priorRender)window.renderDetail=priorRender;if(priorShowDetail)window.showDetail=priorShowDetail;activeSavedKey='';installed=false;return true;}
function detail(){return document.getElementById('detailContent');}
function setText(el,text){if(!el||el.textContent===text)return false;el.textContent=text;return true;}
function lockRateControls(root){let changed=false;root.querySelectorAll?.('.tariff-card,.tariff-more,.board-compact-option,.board-section-title button').forEach(btn=>{if(btn.tagName!=='BUTTON')return;if(!btn.disabled){btn.disabled=true;changed=true;}if(btn.getAttribute('aria-disabled')!=='true'){btn.setAttribute('aria-disabled','true');changed=true;}if(!btn.dataset.noreyoV1014Historical){btn.dataset.noreyoV1014Historical='1';changed=true;}});return changed;}
function sync(){raf=0;const root=detail();if(!root||!activeSavedKey)return false;const badge=root.querySelector('.local-badge');if(!badge)return false;let changed=false;changed=setText(badge,'GESPEICHERTER STAND')||changed;const body=root.querySelector('.detail-body');if(body&&!root.querySelector('.noreyo-v1014-saved-note')){const note=document.createElement('div');note.className='backend-note noreyo-v1014-saved-note';note.innerHTML='<b>Gespeicherter Preisstand</b><p>Dieser Hotelpreis und die angezeigten Tarifdaten stammen aus dem Zeitpunkt des Speicherns und wurden beim Öffnen nicht erneut live geprüft.</p>';body.insertBefore(note,body.firstElementChild||null);changed=true;}root.querySelectorAll?.('.detail-section-head').forEach(head=>{if(head.querySelector('h2')?.textContent?.trim()==='Zimmer & Tarife')changed=setText(head.querySelector('small'),'gespeicherte Tarifauswahl')||changed;});root.querySelectorAll?.('.checkout-total span').forEach(span=>{if(/aktuelle\s+Live-Rate/i.test(span.textContent||'')){span.textContent=String(span.textContent||'').replace(/aktuelle\s+Live-Rate/ig,'gespeicherter Preisstand');changed=true;}});const availability=root.querySelector('.availability-card');if(availability){changed=setText(availability.querySelector('b'),'Gespeicherte Hotelauswahl')||changed;changed=setText(availability.querySelector('p'),'Diese Auswahl wurde mit deinen damaligen Reisedaten gespeichert. Verfügbarkeit und Preis wurden beim Öffnen nicht erneut geprüft.')||changed;}changed=lockRateControls(root)||changed;return changed;}
function schedule(){if(!raf)raf=requestAnimationFrame(sync);}
function observe(){if(observer){observer.disconnect();observer=null;}const root=detail();if(typeof MutationObserver==='undefined'||!root)return false;observer=new MutationObserver(schedule);observer.observe(root,{childList:true,subtree:true});schedule();return true;}
function cleanup(){if(observer){observer.disconnect();observer=null;}if(raf){cancelAnimationFrame(raf);raf=0;}}
function state(){return{activeSavedKey};}
install();observe();window.addEventListener('pagehide',cleanup,{passive:true});window.addEventListener('pageshow',()=>{install();observe();},{passive:true});window.NOREYO_V1014=Object.freeze({BUILD,snapshotByEncoded,savedClone,keyOf,install,restore,detail,setText,lockRateControls,sync,schedule,observe,cleanup,state});
})();