/* NOREYO V5.84 — live-search validation + lifecycle safety */
(function(){
'use strict';
const BUILD='5.84';
let busy=false,timer=0,baseline='',observer=null;
function mode(){const a=document.querySelector('#discover .product-mode.on'),t=(a?.textContent||'').toLowerCase();if(/kreuzfahrt/.test(t))return'cruise';if(/hotel/.test(t)&&!/pauschal/.test(t))return'hotel';if(/flug/.test(t)&&!/pauschal/.test(t))return'flight';try{if(['package','hotel','flight'].includes(productMode))return productMode;}catch(_){}return'package';}
function state(){try{return typeof searchState!=='undefined'&&searchState?searchState:null;}catch(_){return null;}}
function destination(){try{if(typeof dest!=='undefined'&&String(dest||'').trim())return String(dest).trim();}catch(_){}return String(document.querySelector('.destinationInput')?.value||'').trim();}
function validIso(v){if(!/^\d{4}-\d{2}-\d{2}$/.test(String(v||'')))return false;const d=new Date(String(v)+'T00:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===String(v);}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function validate(){const m=mode();if(m==='cruise')return{ok:true};const s=state();if(destination().length<2)return{ok:false,message:'Bitte wähle ein Reiseziel.',planner:'destination'};if(!s)return{ok:true};const airports=(Array.isArray(s.airports)?s.airports:[]).map(v=>String(v||'').trim().toUpperCase()).filter(Boolean);if(m!=='hotel'){if(!airports.length)return{ok:false,message:'Bitte wähle mindestens einen Abflughafen.',planner:'airports'};if(airports.length>6||airports.some(v=>!/^[A-Z]{3}$/.test(v)))return{ok:false,message:'Bitte prüfe deine Abflughäfen.',planner:'airports'};}if(!validIso(s.checkin)||!validIso(s.checkout)||String(s.checkout)<=String(s.checkin))return{ok:false,message:'Bitte prüfe deinen Reisezeitraum.',planner:'dates'};if(String(s.checkin)<today())return{ok:false,message:'Die Anreise liegt in der Vergangenheit.',planner:'dates'};const adults=Math.round(Number(s.adults));const ages=Array.isArray(s.childAges)?s.childAges.map(Number):[];if(!Number.isInteger(adults)||adults<1||adults>9)return{ok:false,message:'Bitte prüfe die Anzahl der Erwachsenen.',planner:'travellers'};if(adults+ages.length>9)return{ok:false,message:'Maximal 9 Reisende pro Suche.',planner:'travellers'};if(ages.some(v=>!Number.isInteger(v)||v<0||v>17))return{ok:false,message:'Bitte ergänze gültige Kinderalter.',planner:'travellers'};if(ages.filter(v=>v<=1).length>adults)return{ok:false,message:'Bitte prüfe die Belegung mit Kleinkindern.',planner:'travellers'};return{ok:true};}
function tell(r){try{if(typeof showToast==='function')showToast(r.message);else if(typeof toast==='function')toast(r.message);else alert(r.message);if(r.planner&&typeof openPlanner==='function')setTimeout(()=>openPlanner(r.planner),0);}catch(_){} }
function signature(){const root=document.getElementById('results'),offers=[...document.querySelectorAll('#offers .offer')];return `${offers.length}:${offers.slice(0,2).map(x=>(x.textContent||'').replace(/\s+/g,' ').trim().slice(0,150)).join('|')}#${(root?.textContent||'').replace(/\s+/g,' ').trim().slice(0,200)}`;}
function release(){busy=false;if(timer)clearTimeout(timer);timer=0;document.querySelectorAll('.liveSearchButton').forEach(b=>{b.disabled=false;b.setAttribute('aria-busy','false');});document.getElementById('results')?.setAttribute('aria-busy','false');}
function settled(){if(!busy||signature()===baseline)return false;if(document.querySelector('#offers .offer'))return true;return /keine (angebote|hotels|flüge|fluege|reisen|ergebnisse)|nichts gefunden|nicht verfügbar|nicht verfugbar|suche fehlgeschlagen|fehler bei der suche|erneut versuchen/i.test(document.getElementById('results')?.textContent||'');}
function guard(event){const button=event.target instanceof Element?event.target.closest('.liveSearchButton,.noreyo-v541-booking-cta'):null;if(!button||mode()==='cruise')return;const check=validate();if(!check.ok){event.preventDefault();event.stopImmediatePropagation();tell(check);return;}if(!button.classList.contains('liveSearchButton'))return;if(busy){event.preventDefault();event.stopImmediatePropagation();return;}busy=true;baseline=signature();button.setAttribute('aria-busy','true');document.getElementById('results')?.setAttribute('aria-busy','true');queueMicrotask(()=>{if(busy)button.disabled=true;});timer=setTimeout(release,15000);}
function observe(){const root=document.getElementById('results');if(!root||observer)return;root.setAttribute('aria-live','polite');root.setAttribute('aria-busy','false');observer=new MutationObserver(()=>{if(settled())release();});observer.observe(root,{childList:true,subtree:true,characterData:true});}
function install(){observe();document.addEventListener('click',guard,true);window.addEventListener('pagehide',release,{passive:true});window.addEventListener('pageshow',()=>{release();observe();},{passive:true});if(typeof MutationObserver!=='undefined')new MutationObserver(observe).observe(document.body,{childList:true,subtree:true});}
window.NOREYO_V584=Object.freeze({BUILD,mode,validIso,validate,signature,release,get busy(){return busy;}});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
