/* NOREYO V9.41 — multi-origin flight search.
   The packed core exposes multiple selected departure airports but only searched
   searchState.airports[0]. Run one provider search per selected origin and
   aggregate the currently available provider responses. */
(()=>{
'use strict';
const BUILD='9.41',MAX_ORIGINS=6;
let installed=false,prior=null;
function validIata(v){return /^[A-Z]{3}$/.test(String(v||'').trim().toUpperCase())}
function origins(values){const out=[];for(const raw of Array.isArray(values)?values:[]){const code=String(raw||'').trim().toUpperCase();if(validIata(code)&&!out.includes(code))out.push(code);if(out.length>=MAX_ORIGINS)break}return out}
function buildOriginBody(base,origin){const body={...(base||{})},legs=Array.isArray(base?.legs)?base.legs.map(x=>({...x})):[];if(legs[0])legs[0].origin=origin;if(legs[1])legs[1].destination=origin;body.legs=legs;return body}
function rows(payload){if(Array.isArray(payload?.data))return payload.data;if(Array.isArray(payload?.data?.data))return payload.data.data;if(Array.isArray(payload?.offers))return payload.offers;if(Array.isArray(payload))return payload;return[]}
function htmlEscape(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function requestOrigin(origin,base){const res=await fetch(providerEndpoint,{method:'POST',headers:{'Content-Type':'application/json','apikey':providerAnon,'Authorization':`Bearer ${providerAnon}`},body:JSON.stringify(buildOriginBody(base,origin))});let p={};try{p=await res.json()}catch(_){}if(!res.ok)throw new Error(p?.message||p?.error?.message||`HTTP ${res.status}`);return{origin,offers:rows(p),payload:p}}
function resultHTML(destIata,results,failures){const total=results.reduce((n,x)=>n+x.offers.length,0);const cards=results.map(x=>`<div class="flight-preview-card"><div class="flight-route"><div><span class="flight-code">${htmlEscape(x.origin)}</span><small>${htmlEscape(fmtDateLong(searchState.checkin))}</small></div><span class="flight-route-line">${svg('plane','icon mini')}</span><div style="text-align:right"><span class="flight-code">${htmlEscape(destIata)}</span><small>${htmlEscape(fmtDateLong(searchState.checkout))} zurück</small></div></div><div class="flight-status"><b>${x.offers.length?`${x.offers.length} Flugangebote`:'Keine Flugangebote'}</b><br>${x.offers.length?'Live-Antwort für diesen Abflughafen empfangen.':'Die Schnittstelle war erreichbar, lieferte für diesen Abflughafen aber keine Angebote.'}</div></div>`).join('');const fail=failures.length?`<div class="backend-note"><b>${failures.length} Abflughafen${failures.length===1?'':'/-häfen'} konnte${failures.length===1?'':'n'} nicht geprüft werden</b><p>${failures.map(x=>htmlEscape(x.origin)).join(', ')} · Deine Auswahl bleibt erhalten. Bitte erneut versuchen.</p></div>`:'';return `<div class="flight-preview"><div class="flight-status" style="margin:0 0 12px"><b>${total} Flugangebote aus ${results.length} geprüften Abflughafen${results.length===1?'':'/-häfen'}</b><br>Jeder ausgewählte Abflughafen wurde separat live geprüft. Flugpreise bleiben vom Hotelpreis getrennt.</div>${cards}${fail}</div>`}
async function multiSearchFlights(){const iata=destinationIata[String(dest).toLowerCase()];if(!iata){openPlanner('destination');showToast('Bitte zuerst ein Ziel wählen');return}const selected=origins(searchState.airports);if(!selected.length){openPlanner('airports');showToast('Bitte mindestens einen Abflughafen wählen');return}if(selected.length===1&&typeof prior==='function')return prior();const base=flightRequestBody();openPlannerShell('Flüge',`<div class="loading-panel" style="margin:0"><span class="search-spinner"></span><b>${selected.length} Abflughäfen werden geprüft</b><p>${selected.map(htmlEscape).join(', ')} → ${htmlEscape(iata)}</p></div>`);const settled=await Promise.allSettled(selected.map(origin=>requestOrigin(origin,base)));const results=[],failures=[];settled.forEach((s,i)=>s.status==='fulfilled'?results.push(s.value):failures.push({origin:selected[i],error:s.reason}));const body=document.getElementById('plannerBody');if(body)body.innerHTML=resultHTML(iata,results,failures)}
function install(){if(installed)return false;try{if(typeof searchFlights!=='function')return false;prior=searchFlights;searchFlights=multiSearchFlights;installed=true;return true}catch(_){return false}}
function restore(){if(!installed)return false;try{if(prior)searchFlights=prior}catch(_){}installed=false;return true}
install();window.NOREYO_V941=Object.freeze({BUILD,MAX_ORIGINS,validIata,origins,buildOriginBody,rows,htmlEscape,requestOrigin,resultHTML,multiSearchFlights,install,restore});
})();