(function(){
'use strict';
const BUILD='5.56';
let lockedY=0,currentData=null;
const months={januar:0,februar:1,maerz:2,marz:2,april:3,mai:4,juni:5,juli:6,august:7,september:8,oktober:9,november:10,dezember:11};
const monthLabel=['Januar','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember'];
const airports={duesseldorf:'DUS',dusseldorf:'DUS',dus:'DUS',koeln:'CGN',koln:'CGN','koeln/bonn':'CGN','koln/bonn':'CGN',cgn:'CGN',paderborn:'PAD',pad:'PAD',muenster:'FMO',munster:'FMO',fmo:'FMO',frankfurt:'FRA',fra:'FRA',hannover:'HAJ',haj:'HAJ',dortmund:'DTM',dtm:'DTM',hamburg:'HAM',ham:'HAM',muenchen:'MUC',munchen:'MUC',muc:'MUC',berlin:'BER',ber:'BER'};
const prefDefs=[
 {key:'Zimmer0',label:'Balkon',re:/\b(balkon|privater balkon)\b/i},
 {key:'Zimmer1',label:'Meerblick',re:/\b(meerblick|sea view)\b/i},
 {key:'Zimmer2',label:'Terrasse',re:/\bterrasse\b/i},
 {key:'Hotel0',label:'Mind. 4 Sterne',re:/\b(4\s*sterne|vier\s*sterne|mindestens\s*4\s*sterne)\b/i},
 {key:'Hotel1',label:'Adults Only',re:/\b(adults?\s*only|erwachsenenhotel|nur erwachsene)\b/i},
 {key:'Hotel4',label:'Spa / Wellness',re:/\b(spa|wellness)\b/i},
 {key:'Hotel5',label:'Fitness',re:/\b(fitness|fitnessraum|gym)\b/i},
 {key:'Lage0',label:'Sandstrand',re:/\bsandstrand\b/i},
 {key:'Lage1',label:'Direkt am Strand',re:/\b(direkt am strand|strandlage|am strand)\b/i},
 {key:'Lage2',label:'Ruhige Lage',re:/\b(ruhig|ruhige lage|keine partyzone)\b/i},
 {key:'Lage3',label:'Restaurants zu Fuß',re:/\b(restaurants? zu fuss|restaurants? fusslaufig|fusslaufige restaurants?)\b/i},
 {key:'Lage4',label:'Kurzer Transfer',re:/\b(kurzer transfer|transfer.{0,10}(max|unter|kurz))\b/i},
 {key:'Preis2',label:'Kostenlos stornierbar',re:/\b(kostenlos stornierbar|kostenfrei stornierbar|flexibel stornierbar)\b/i},
 {key:'Flug0',label:'Direktflug',re:/\b(direktflug|nonstop|ohne zwischenlandung)\b/i},
 {key:'Flug1',label:'Aufgabegepäck',re:/\b(aufgabegepack|koffer inklusive|gepack inklusive)\b/i}
];
function norm(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss');}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function fmtEuro(n){return new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);}
function mode(){const a=document.querySelector('#discover .product-mode.on');const t=norm(a?.textContent||'');if(t.includes('kreuzfahrt'))return'cruise';if(t.includes('hotel'))return'hotel';if(t.includes('flug'))return'flight';try{if(typeof productMode==='string')return productMode;}catch(_){ }return'package';}
function modeLabel(m){return m==='hotel'?'Hotel':m==='flight'?'Flug':m==='cruise'?'Kreuzfahrt':'Pauschalreise';}
function copyFor(m){return m==='hotel'?['Sag NOREYO, wie dein Hotel sein soll.','z. B. Mallorca im September, direkt am Strand, ruhig, Balkon wäre schön, max. 900 € pro Person.']:m==='flight'?['Sag NOREYO, wie du fliegen willst.','z. B. Im Oktober für 7 Tage nach Mallorca, ab Düsseldorf oder Köln, Direktflug, max. 350 € pro Person.']:m==='cruise'?['Sag NOREYO, wie deine Kreuzfahrt sein soll.','z. B. Mittelmeer im September, 7–9 Nächte, Balkonkabine, maximal 2.500 € für zwei Personen.']:['Sag NOREYO, wie du reisen willst.','z. B. Mallorca im September, 7 Tage, All Inclusive, direkt am Strand. Balkon wäre schön. Max. 1.800 € für zwei.'];}
function exampleSet(m){if(m==='hotel')return['Mallorca · Strand · Balkon · ruhig','Dubai · 4 Sterne · Spa · Frühstück'];if(m==='flight')return['Mallorca · ab DUS · Direktflug','Dubai · ab CGN · Aufgabegepäck'];if(m==='cruise')return['Mittelmeer · 7–9 Nächte · Balkon','Kanaren · 10–14 Nächte · Suite'];return['Mallorca · All Inclusive · Strand · Balkon','Kreta · 4 Sterne · ruhig · Direktflug'];}
function shell(){let w=document.getElementById('noreyoAi556');if(w)return w;w=document.createElement('div');w.id='noreyoAi556';w.className='noreyo-v556-backdrop';w.innerHTML='<section class="noreyo-v556-sheet" role="dialog" aria-modal="true" aria-labelledby="noreyoAi556Title"><div class="noreyo-v556-handle"></div><header class="noreyo-v556-head"><div class="noreyo-v556-headcopy"><div class="noreyo-v556-eyebrow"><i></i>NOREYO AI · WUNSCHSUCHE</div><h2 id="noreyoAi556Title"></h2></div><button type="button" class="noreyo-v556-close" aria-label="Schließen">×</button></header><div class="noreyo-v556-scroll"><div class="noreyo-v556-promise"><span><b>1 Satz</b>statt Filterchaos</span><span><b>Pflicht vs. Wunsch</b>wird unterschieden</span><span><b>Erst prüfen</b>dann übernehmen</span></div><p class="noreyo-v556-intro">Beschreib deinen Urlaub ganz normal. Ziel, Zeitraum, Budget und Wünsche werden automatisch erkannt.</p><div class="noreyo-v556-inputwrap"><textarea id="noreyoAi556Text" maxlength="500"></textarea><span class="noreyo-v556-counter">0 / 500</span></div><div class="noreyo-v556-examples"></div><button type="button" class="noreyo-v556-analyze"><span class="star">✦</span> Wunsch analysieren</button><div id="noreyoAi556Result"></div></div></section>';document.body.appendChild(w);
 w.addEventListener('click',e=>{if(e.target===w)closeAI();});w.querySelector('.noreyo-v556-close').addEventListener('click',closeAI);w.querySelector('.noreyo-v556-analyze').addEventListener('click',analyzeInput);const ta=w.querySelector('#noreyoAi556Text');ta.addEventListener('input',()=>{w.querySelector('.noreyo-v556-counter').textContent=ta.value.length+' / 500';});ta.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter')analyzeInput();});return w;}
function syncViewport(){const w=document.getElementById('noreyoAi556');if(!w||!w.classList.contains('show'))return;const vv=window.visualViewport;if(!vv)return;w.style.height=vv.height+'px';w.style.top=vv.offsetTop+'px';const sh=w.querySelector('.noreyo-v556-sheet');if(sh)sh.style.maxHeight=Math.max(360,Math.min(820,vv.height-4))+'px';}
function lockPage(){lockedY=window.scrollY||0;document.body.classList.add('noreyo-v556-lock');document.body.style.top=(-lockedY)+'px';}
function unlockPage(){document.body.classList.remove('noreyo-v556-lock');document.body.style.top='';window.scrollTo(0,lockedY);}
function openAI(){const w=shell(),m=mode(),copy=copyFor(m);w.dataset.mode=m;w.querySelector('#noreyoAi556Title').textContent=copy[0];const ta=w.querySelector('#noreyoAi556Text');ta.placeholder=copy[1];w.querySelector('#noreyoAi556Result').innerHTML='';currentData=null;w.querySelector('.noreyo-v556-examples').innerHTML=exampleSet(m).map(x=>'<button type="button" class="noreyo-v556-example">'+esc(x)+'</button>').join('');w.querySelectorAll('.noreyo-v556-example').forEach(b=>b.addEventListener('click',()=>{ta.value=b.textContent||'';ta.dispatchEvent(new Event('input'));ta.focus();}));lockPage();w.classList.add('show');requestAnimationFrame(syncViewport);}
function closeAI(){const w=document.getElementById('noreyoAi556');if(!w||!w.classList.contains('show'))return;document.activeElement?.blur?.();w.classList.remove('show');w.style.height='';w.style.top='';unlockPage();}
function knownDestination(text){const t=norm(text);let choices=[];try{if(typeof destinationChoices!=='undefined'&&Array.isArray(destinationChoices))choices=destinationChoices.map(x=>Array.isArray(x)?x[0]:x).filter(Boolean);}catch(_){ }if(!choices.length)choices=['Mallorca','Kreta','Santorini','Rhodos','Kos','Antalya','Teneriffa','Gran Canaria','Fuerteventura','Lanzarote','Sardinien','Algarve','Ibiza','Menorca','Hurghada','Dubai','Malediven','Ägypten','Türkei','Griechenland','Spanien','Portugal'];return choices.sort((a,b)=>String(b).length-String(a).length).find(n=>{const q=norm(n).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return new RegExp('(^|[^a-z0-9])'+q+'([^a-z0-9]|$)','i').test(t);})||'';}
function parseBudget(text){const t=norm(text);const perPerson=/\b(pro person|p\.?\s*p\.?|je person)\b/.test(t);const res=[/(?:max(?:imal)?\.?|bis|budget(?: von)?|hoechstens|hochstens)\s*(?:ca\.?\s*)?([0-9][0-9\.\s]{2,})\s*(?:€|euro)/i,/([0-9][0-9\.\s]{2,})\s*(?:€|euro)\s*(?:max(?:imal)?\.?|budget|insgesamt|pro person|p\.?\s*p\.?)?/i];for(const re of res){const m=t.match(re);if(m){const n=Number(m[1].replace(/[\.\s]/g,''));if(Number.isFinite(n)&&n>=100&&n<=50000)return{amount:n,perPerson};}}return null;}
function parseAdults(text){const t=norm(text);let m=t.match(/\b([1-6])\s*(?:erwachsene|personen|person)\b/);if(m)return Number(m[1]);if(/\bzu zweit\b/.test(t))return 2;const words={einer:1,eine:1,einem:1,zwei:2,drei:3,vier:4,fuenf:5,funf:5,sechs:6};m=t.match(/\b(einer|eine|einem|zwei|drei|vier|fuenf|funf|sechs)\s*(?:erwachsene|personen|person)?\b/);if(m&&/(fur|fuer|mit|zu)\s+(einer|eine|einem|zwei|drei|vier|fuenf|funf|sechs)/.test(t.slice(Math.max(0,(m.index||0)-8),(m.index||0)+m[0].length)))return words[m[1]];return null;}
function parseAirports(text){const t=norm(text),out=[];Object.entries(airports).forEach(([name,code])=>{if(new RegExp('(^|[^a-z0-9])'+name.replace('/','\\/')+'([^a-z0-9]|$)').test(t)&&!out.includes(code))out.push(code);});return out;}
function parseMeal(text){const t=norm(text);if(/\ball\s*inclusive\b|\ball-inclusive\b/.test(t))return{code:'AI',label:'All Inclusive'};if(/\bvollpension\b/.test(t))return{code:'FB',label:'Vollpension'};if(/\bhalbpension\b/.test(t))return{code:'HB',label:'Halbpension'};if(/\bfruehstueck\b|\bfruhstuck\b/.test(t))return{code:'BB',label:'Frühstück'};if(/\bnur uebernachtung\b|\bohne verpflegung\b/.test(t))return{code:'RO',label:'Nur Übernachtung'};return null;}
function parseDuration(text){const t=norm(text);let m=t.match(/\b([3-9]|1[0-9]|2[0-1])\s*[-–]\s*([3-9]|1[0-9]|2[0-1])\s*(?:tage|naechte|nachte)\b/);if(m)return{days:Math.round((+m[1]+ +m[2])/2),label:m[1]+'–'+m[2]+' '+(/nacht/.test(m[0])?'Nächte':'Tage')};m=t.match(/\b([3-9]|1[0-9]|2[0-1])\s*(?:tage|naechte|nachte)\b/);if(m)return{days:+m[1],label:m[1]+' '+(/nacht/.test(m[0])?'Nächte':'Tage')};m=t.match(/\b(eine|zwei)\s*wochen?\b/);if(m)return{days:m[1]==='zwei'?14:7,label:m[1]==='zwei'?'2 Wochen':'1 Woche'};return null;}
function parseDate(text,duration){const raw=String(text||''),t=norm(raw),now=new Date();const iso=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');const yr=y=>{let n=y?+y:now.getFullYear();if(n<100)n+=2000;return n;};let m=raw.match(/\b(\d{1,2})[.\/]\s*(\d{1,2})(?:[.\/]\s*(\d{2,4}))?\.?\s*(?:bis|-|–)\s*(\d{1,2})[.\/]\s*(\d{1,2})(?:[.\/]\s*(\d{2,4}))?/);if(m){const a=new Date(yr(m[3]),+m[2]-1,+m[1],12),b=new Date(yr(m[6]||m[3]),+m[5]-1,+m[4],12);if(b>a)return{checkin:iso(a),checkout:iso(b),label:m[1]+'.'+m[2]+'. – '+m[4]+'.'+m[5]+'.',flex:false};}m=t.match(/\b(?:ab|vom)?\s*(\d{1,2})[.\s]+(januar|februar|maerz|marz|april|mai|juni|juli|august|september|oktober|november|dezember)(?:\s*(20\d{2}))?/);if(m){const mo=months[m[2]],y0=+(m[3]||now.getFullYear());let a=new Date(y0,mo,+m[1],12);if(a<now&&!m[3])a=new Date(y0+1,mo,+m[1],12);const b=new Date(a);b.setDate(b.getDate()+(duration?.days||7));return{checkin:iso(a),checkout:iso(b),label:'ab '+m[1]+'. '+monthLabel[mo],flex:false};}for(const [name,mo] of Object.entries(months)){if(!new RegExp('(^|[^a-z])'+name+'([^a-z]|$)').test(t))continue;let ym=t.match(new RegExp(name+'\\s*(20\\d{2})')),y=+(ym?.[1]||now.getFullYear());const test=new Date(y,mo,1,12);if(test<new Date(now.getFullYear(),now.getMonth(),1)&&!ym)y++;return{month:mo,year:y,label:monthLabel[mo]+' '+y,flex:true};}if(/\b(nachsten|naechsten) monat\b/.test(t)){let y=now.getFullYear(),mo=now.getMonth()+1;if(mo>11){mo=0;y++;}return{month:mo,year:y,label:monthLabel[mo]+' '+y,flex:true};}return null;}
function hardNear(text,re){const t=norm(text),m=t.match(re);if(!m)return false;const i=m.index||0,e=i+m[0].length,b=t.slice(Math.max(0,i-34),i),a=t.slice(e,Math.min(t.length,e+30));return/(muss|unbedingt|pflicht|auf jeden fall|zwingend|nur)\s*(?:sein|ist|:)?\s*$/.test(b)||/^\s*(?:muss|unbedingt|pflicht|auf jeden fall|zwingend)/.test(a);}
function parsePrefs(text){const t=norm(text),out=[];for(const d of prefDefs){if(!d.re.test(t))continue;const explicit=d.key==='Hotel0'&&/mindestens\s*4\s*sterne/.test(t);out.push({key:d.key,label:d.label,state:(explicit||hardNear(t,d.re))?'must':'wish'});}return out;}
function parseNotes(text){const t=norm(text),n=[];if(/nicht abgelegen|nicht zu abgelegen/.test(t))n.push('Nicht abgelegen');if(/modern(es|e|er)? hotel|modern eingerichtet/.test(t))n.push('Modern');if(/klein(es|e|er)? hotel|boutique/.test(t))n.push('Eher klein / Boutique');if(/zentral|innenstadt/.test(t))n.push('Zentral');if(/familienfreundlich|kinderfreundlich/.test(t))n.push('Familienfreundlich');return n;}
function parseCruise(text,duration){const t=norm(text),o={};[['Mittelmeer','mittelmeer'],['Nordeuropa','nordeuropa'],['Karibik','karibik'],['Kanaren','kanaren'],['Orient','orient']].forEach(([l,k])=>{if(t.includes(k))o.area=l;});if(/flusskreuzfahrt|\bfluss\b/.test(t))o.type='Flusskreuzfahrt';else if(/hochseekreuzfahrt|hochsee/.test(t))o.type='Hochseekreuzfahrt';if(/balkonkabine|balkon kabine|\bbalkon\b/.test(t))o.cabin='Balkonkabine';else if(/suite/.test(t))o.cabin='Suite';else if(/aussenkabine|aussen kabine/.test(t))o.cabin='Außenkabine';else if(/innenkabine|innen kabine/.test(t))o.cabin='Innenkabine';if(duration)o.duration=duration.days<=6?'3–6 Nächte':duration.days<=9?'7–9 Nächte':duration.days<=14?'10–14 Nächte':'15+ Nächte';return o;}
function analyze(text,m){const duration=parseDuration(text),adults=parseAdults(text);return{mode:m,raw:text,destination:knownDestination(text),date:parseDate(text,duration),duration,adults,budget:parseBudget(text),airports:parseAirports(text),meal:parseMeal(text),prefs:m==='cruise'?[]:parsePrefs(text),notes:parseNotes(text),cruise:m==='cruise'?parseCruise(text,duration):null};}
function chip(label,kind){return'<span class="noreyo-v556-chip '+(kind||'')+'"><i>'+(kind==='must'?'●':'✓')+'</i>'+esc(label)+'</span>';}
function render(data){currentData=data;const core=[],must=[],wish=[],notes=data.notes.slice();if(data.destination)core.push('Ziel · '+data.destination);if(data.date)core.push('Zeitraum · '+data.date.label+(data.date.flex?' · flexibel':''));if(data.duration)core.push('Dauer · '+data.duration.label);if(data.adults)core.push('Reisende · '+data.adults+' '+(data.adults===1?'Person':'Personen'));if(data.budget)core.push('Budget · '+fmtEuro(data.budget.amount)+(data.budget.perPerson?' p. P.':''));if(data.airports.length)core.push('Abflug · '+data.airports.join(' / '));if(data.meal&&data.mode!=='flight')core.push('Verpflegung · '+data.meal.label);data.prefs.forEach(p=>(p.state==='must'?must:wish).push(p.label));if(data.cruise)Object.entries(data.cruise).forEach(([k,v])=>{if(v)core.push(({area:'Gebiet',type:'Art',cabin:'Kabine',duration:'Dauer'})[k]+' · '+v);});const missing=[];if(data.mode!=='cruise'&&!data.destination)missing.push('Reiseziel');if(!data.date)missing.push('Zeitraum');if(data.mode==='flight'&&!data.airports.length)missing.push('Abflughafen');if(data.mode==='cruise'&&!data.cruise?.area)missing.push('Reisegebiet');const recognized=core.length+must.length+wish.length+notes.length,confidence=Math.min(99,Math.max(62,58+recognized*6-(missing.length*4)));const g=(label,arr,kind)=>arr.length?'<div class="noreyo-v556-group"><p class="noreyo-v556-grouplabel">'+label+'</p><div class="noreyo-v556-chips">'+arr.map(x=>chip(x,kind)).join('')+'</div></div>':'';const html='<div class="noreyo-v556-result"><div class="noreyo-v556-resulthead"><span class="noreyo-v556-resulticon">✓</span><div><small>SO HABE ICH DICH VERSTANDEN</small><b>'+esc(modeLabel(data.mode))+'</b></div><span class="noreyo-v556-confidence">'+confidence+'% erkannt</span></div>'+g('Reise',core,'')+g('Pflicht · muss passen',must,'must')+g('Wünsche · schön wenn es passt',wish,'')+(notes.length?'<div class="noreyo-v556-group"><p class="noreyo-v556-grouplabel">Weitere Hinweise</p><div class="noreyo-v556-chips">'+notes.map(x=>chip(x,'note')).join('')+'</div></div>':'')+(missing.length?'<p class="noreyo-v556-open"><b>Noch offen:</b> '+esc(missing.join(' · '))+'. Du kannst das anschließend in der normalen Suche ergänzen.</p>':'')+'<div class="noreyo-v556-safe"><span>✓</span><div>NOREYO startet noch nichts automatisch. Du prüfst zuerst, was übernommen wird.</div></div><div class="noreyo-v556-actions"><button type="button" class="noreyo-v556-edit">Text ändern</button><button type="button" class="noreyo-v556-apply">In Suche übernehmen →</button></div></div>';const r=document.getElementById('noreyoAi556Result');r.innerHTML=html;r.querySelector('.noreyo-v556-edit').addEventListener('click',()=>document.getElementById('noreyoAi556Text')?.focus());r.querySelector('.noreyo-v556-apply').addEventListener('click',applyCurrent);setTimeout(()=>r.scrollIntoView({block:'nearest',behavior:'smooth'}),40);}
function analyzeInput(){const ta=document.getElementById('noreyoAi556Text'),text=String(ta?.value||'').trim(),r=document.getElementById('noreyoAi556Result');if(text.length<4){r.innerHTML='<div class="noreyo-v556-error">Schreib mir kurz, was dir bei der Reise wichtig ist.</div>';ta?.focus();return;}render(analyze(text,mode()));}
function applyCore(data){try{if(data.destination&&typeof syncDest==='function')syncDest(data.destination);if(data.destination&&data.mode==='hotel'&&typeof setHotelQuery==='function')setHotelQuery(data.destination);if(data.adults&&typeof searchState!=='undefined')searchState.adults=Math.max(1,Math.min(6,data.adults));if(data.airports.length&&typeof searchState!=='undefined')searchState.airports=data.airports.slice(0,5);if(data.date&&!data.date.flex&&typeof searchState!=='undefined'){searchState.checkin=data.date.checkin;searchState.checkout=data.date.checkout;}if(data.meal&&data.mode!=='flight'&&typeof mealPlanFilter!=='undefined')mealPlanFilter=data.meal.code;if(data.budget&&typeof limits!=='undefined'){let amount=data.budget.amount;if(data.budget.perPerson){let a=data.adults;try{if(!a&&typeof searchState!=='undefined')a=searchState.adults;}catch(_){ }amount*=Math.max(1,a||2);}limits.maxHotelPrice=amount;}if(typeof states!=='undefined')data.prefs.forEach(p=>{if(p.key in states)states[p.key]=p.state;});if(typeof updateSearchUI==='function')updateSearchUI();if(typeof refreshQuickStates==='function')refreshQuickStates();if(typeof updateCounts==='function')updateCounts();if(typeof persistState==='function')persistState();}catch(e){console.warn('NOREYO AI '+BUILD+' apply',e);}}
function selectCruise(kind,value){return new Promise(resolve=>{const btn=document.querySelector('#discover [data-cruise-picker="'+kind+'"]');if(!btn){resolve();return;}btn.click();setTimeout(()=>{const opt=[...document.querySelectorAll('.noreyo-v552-sheet-options [data-cruise-value]')].find(b=>(b.getAttribute('data-cruise-value')||'')===value);if(opt)opt.click();else document.querySelector('[data-close-cruise-sheet]')?.click();resolve();},45);});}
async function applyCurrent(){const data=currentData;if(!data)return;applyCore(data);if(data.mode==='cruise'&&data.cruise){for(const [k,v] of Object.entries(data.cruise))if(v)await selectCruise(k,v);}closeAI();try{if(typeof showToast==='function')showToast('NOREYO hat deinen Wunsch übernommen');}catch(_){ }if(data.date?.flex){setTimeout(()=>{try{if(typeof openPlanner==='function')openPlanner('dates');}catch(_){ }},260);}else{setTimeout(()=>document.querySelector('#discover .search-card')?.scrollIntoView({behavior:'smooth',block:'start'}),180);}}
function intercept(e){const b=e.target?.closest?.('.noreyo-v555-ai-launch');if(!b)return;e.preventDefault();e.stopImmediatePropagation();openAI();}
document.addEventListener('click',intercept,true);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.getElementById('noreyoAi556')?.classList.contains('show'))closeAI();});window.visualViewport?.addEventListener('resize',syncViewport);window.visualViewport?.addEventListener('scroll',syncViewport);
})();