/* NOREYO V11.62 — real profile account surface backed by checkout auth session.
   Replaces the packed fake profile-edit toast with truthful Supabase account state.
   Uses the V11.58 passwordless auth boundary; never renders access/refresh tokens. */
(function(){
'use strict';
const BUILD='11.62';
let observer=null,raf=0,bound=false;
function auth(){return window.NOREYO_V1158||null;}
function model(){const a=auth();if(!a)return{authenticated:false,email:'',userId:''};try{const s=a.session?.();const ok=!!s?.access_token&&!!s?.user_id&&!!a.authenticated?.();return{authenticated:ok,email:ok?String(s.email||''):'',userId:ok?String(s.user_id||''):''};}catch(_){return{authenticated:false,email:'',userId:''};}}
function root(){return document.getElementById('profile');}
function hero(){return root()?.querySelector('.profile-hero')||null;}
function ensurePanel(){const r=root();if(!r)return null;let panel=r.querySelector('.noreyo-v1162-account');if(panel)return panel;panel=document.createElement('section');panel.className='noreyo-v1162-account';panel.innerHTML='<div class="noreyo-v1162-copy"></div><div class="noreyo-v1162-login"><input class="noreyo-v1162-email" type="email" autocomplete="email" inputmode="email" placeholder="E-Mail-Adresse" aria-label="E-Mail-Adresse für NOREYO Anmeldung"><button type="button" class="dark-btn noreyo-v1162-send">Anmeldelink senden</button></div><button type="button" class="noreyo-v1162-logout" hidden>Abmelden</button><div class="noreyo-v1162-status" role="status" aria-live="polite" aria-atomic="true"></div>';const h=hero();if(h?.nextSibling)h.parentNode.insertBefore(panel,h.nextSibling);else if(h)h.parentNode.appendChild(panel);else r.prepend(panel);return panel;}
function enhanceHero(m=model()){const h=hero();if(!h)return false;let changed=false;h.removeAttribute('onclick');if(h.getAttribute('role')!=='button'){h.setAttribute('role','button');changed=true;}if(h.getAttribute('tabindex')!=='0'){h.setAttribute('tabindex','0');changed=true;}const b=h.querySelector('b'),small=h.querySelector('small');const title=m.authenticated?'Mein Konto':'Anmelden';const sub=m.authenticated?(m.email||'Sichere Session aktiv'):'Für eine spätere Buchung sicher anmelden';if(b&&b.textContent!==title){b.textContent=title;changed=true;}if(small&&small.textContent!==sub){small.textContent=sub;changed=true;}const label=m.authenticated?`Mein Konto${m.email?`, ${m.email}`:''}`:'Bei NOREYO anmelden';if(h.getAttribute('aria-label')!==label){h.setAttribute('aria-label',label);changed=true;}return changed;}
function render(){raf=0;const r=root();if(!r)return false;const m=model(),panel=ensurePanel();if(!panel)return false;let changed=enhanceHero(m);const copy=panel.querySelector('.noreyo-v1162-copy'),login=panel.querySelector('.noreyo-v1162-login'),logout=panel.querySelector('.noreyo-v1162-logout');const text=m.authenticated?`Angemeldet${m.email?` als ${m.email}`:''}. Diese Session wird auch für den sicheren Checkout verwendet.`:'Noch nicht angemeldet. Die Anmeldung wird erst vor einer späteren Buchung benötigt.';if(copy&&copy.textContent!==text){copy.textContent=text;changed=true;}if(login)login.hidden=m.authenticated;if(logout)logout.hidden=!m.authenticated;const intro=r.querySelector('.simple-intro h1');if(intro&&intro.textContent!=='Deine Reisepräferenzen, auf diesem Gerät gespeichert.'){intro.textContent='Deine Reisepräferenzen, auf diesem Gerät gespeichert.';changed=true;}return changed;}
function focusLogin(){const p=ensurePanel();const input=p?.querySelector('.noreyo-v1162-email');if(input&&!input.closest('.noreyo-v1162-login')?.hidden){try{input.focus({preventScroll:false});input.scrollIntoView?.({block:'center',behavior:'smooth'});}catch(_){input.focus?.();}}}
async function send(panel){const a=auth(),input=panel?.querySelector('.noreyo-v1162-email'),status=panel?.querySelector('.noreyo-v1162-status'),btn=panel?.querySelector('.noreyo-v1162-send');if(!a?.sendMagicLink)return;if(btn){btn.disabled=true;btn.textContent='Link wird gesendet …';}try{await a.sendMagicLink(input?.value||'');if(status)status.textContent='Anmeldelink gesendet. Öffne ihn auf diesem Gerät und kehre zu NOREYO zurück.';}catch(e){if(status)status.textContent=String(e?.message||e||'Anmeldung fehlgeschlagen.');}finally{if(btn){btn.disabled=false;btn.textContent='Anmeldelink senden';}}}
function logout(){try{auth()?.clear?.();}catch(_){}try{window.NOREYO_V1160?.clear?.();}catch(_){}render();return true;}
function onClick(e){const h=e.target?.closest?.('#profile .profile-hero');if(h){e.preventDefault();e.stopPropagation();focusLogin();return;}const sendBtn=e.target?.closest?.('.noreyo-v1162-send');if(sendBtn){e.preventDefault();e.stopPropagation();send(sendBtn.closest('.noreyo-v1162-account'));return;}if(e.target?.closest?.('.noreyo-v1162-logout')){e.preventDefault();e.stopPropagation();logout();}}
function onKey(e){const h=e.target?.closest?.('#profile .profile-hero');if(!h||(e.key!=='Enter'&&e.key!==' '))return;e.preventDefault();focusLogin();}
function schedule(){if(!raf)raf=requestAnimationFrame(render);}
function install(){if(bound)return false;bound=true;if(typeof MutationObserver!=='undefined'&&document.body){observer=new MutationObserver(schedule);observer.observe(document.body,{subtree:true,childList:true});}document.addEventListener('click',onClick,true);document.addEventListener('keydown',onKey,true);schedule();return true;}
function cleanup(){if(observer){observer.disconnect();observer=null;}if(bound){document.removeEventListener('click',onClick,true);document.removeEventListener('keydown',onKey,true);bound=false;}if(raf){cancelAnimationFrame(raf);raf=0;}}
install();window.addEventListener('pagehide',cleanup,{passive:true});window.addEventListener('pageshow',install,{passive:true});
window.NOREYO_V1162=Object.freeze({BUILD,auth,model,root,hero,ensurePanel,enhanceHero,render,focusLogin,send,logout,onClick,onKey,schedule,install,cleanup});
})();