/* NOREYO V5.72 — natural-search family + traveller safety */
(function(){
'use strict';
const BUILD='5.72';
let pendingFamily=null,plannerRequested=false,adultSnapshot=null;
function norm(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss');}
function num(v){const m={ein:1,eine:1,einen:1,einem:1,einer:1,zwei:2,drei:3,vier:4,fuenf:5,funf:5,sechs:6,sieben:7,acht:8,neun:9};const s=norm(v).trim();return /^\d+$/.test(s)?Number(s):(m[s]??null);}
function explicitAdults(text){const t=norm(text);return /\bzu zweit\b/.test(t)||/\b(?:[1-9]|ein(?:e|en|em|er)?|zwei|drei|vier|fuenf|funf|sechs|sieben|acht|neun)\s+(?:erwachsen(?:e|er|en)?|personen?|reisende)\b/.test(t);}
function parseAdults(text){const t=norm(text);let m=t.match(/\b([1-9]|ein(?:e|en|em|er)?|zwei|drei|vier|fuenf|funf|sechs|sieben|acht|neun)\s+(?:erwachsen(?:e|er|en)?|personen?|reisende)\b/);if(m)return num(m[1]);if(/\bzu zweit\b/.test(t))return 2;return null;}
function noChildren(text){const t=norm(text);return /\b(?:ohne|keine|kein)\s+(?:kinder|kind|baby)\b/.test(t)||/\bnur\s+erwachsene\b/.test(t);}
function parseCount(text){const t=norm(text);if(noChildren(t))return 0;let m=t.match(/\b([1-8]|ein(?:e|en|em|er)?|zwei|drei|vier|fuenf|funf|sechs|sieben|acht)\s+(?:kinder|kindern|kind|babys|baby)\b/);if(m)return num(m[1]);if(/\b(?:mit\s+)?(?:einem\s+)?baby\b/.test(t))return 1;return null;}
function addAge(out,v){const n=Number(v);if(Number.isInteger(n)&&n>=0&&n<=17)out.push(n);}
function parseAges(text){const t=norm(text),out=[];let m;for(const re of [/(?:kinder|kindern|kinderalter|alter der kinder)[^.!?;]{0,55}?(\d{1,2}(?:\s*(?:,|und|&|\/)\s*\d{1,2})+)(?:\s*jahre?)?/g,/(?:mit|und)\s+(\d{1,2}(?:\s*(?:,|und|&|\/)\s*\d{1,2})+)\s*jahre?(?:\s+alt)?/g])while((m=re.exec(t)))for(const n of (m[1].match(/\d{1,2}/g)||[]))addAge(out,n);if(out.length)return out;for(const re of [/\b(?:kind|sohn|tochter)\s*(?:ist|mit|,)?\s*(\d{1,2})\s*(?:jahre?|jahr|j\.)\b/g,/\b(\d{1,2})\s*(?:jahre?|jahr)\s*(?:altes?|alte|alter)\s*(?:kind|sohn|tochter)\b/g])while((m=re.exec(t)))addAge(out,m[1]);if(out.length)return out;const baby=t.match(/\bbaby[^.!?;]{0,24}?(\d{1,2})\s*(?:monate?|monat)\b/);if(baby){addAge(out,0);return out;}const one=t.match(/\b(?:kinder|kindern|kind|babys|baby)\b[^.!?;]{0,24}?(\d{1,2})\s*(?:jahre?|jahr|j\.)\b/);if(one)addAge(out,one[1]);return out;}
function parseFamily(text){const t=norm(text),adults=parseAdults(t),count=parseCount(t),ages=parseAges(t),intent=count!==null||ages.length>0||/\b(?:kinder|kindern|kind|baby|sohn|tochter|familie)\b/.test(t);if(!intent)return null;if(count===0)return{adults,count:0,ages:[],complete:true,errors:[]};const c=count===null?ages.length:count,errors=[];if(!c)errors.push('Kinderanzahl fehlt');if(ages.length!==c)errors.push(`Bitte Alter für ${c||'alle'} Kinder angeben`);if(adults&&adults+c>9)errors.push('Maximal 9 Reisende pro Suche');if(adults&&ages.filter(v=>v<=1).length>adults)errors.push('Maximal ein Kleinkind unter 2 pro Erwachsenem');return{adults,count:c,ages,complete:c>0&&ages.length===c&&!errors.length,errors};}
function state(){try{return typeof searchState!=='undefined'&&searchState?searchState:null;}catch(_){return null;}}
function refresh(){try{if(typeof updateSearchUI==='function')updateSearchUI();}catch(_){}try{if(typeof persistState==='function')persistState();}catch(_){}}
function aiText(){return document.getElementById('noreyoAi556Text')?.value||document.querySelector('#discover [data-v571-text]')?.value||'';}
function apply(text=aiText()){const f=parseFamily(text),s=state();if(!f){pendingFamily=null;return f;}if(f.complete&&s){if(f.adults)s.adults=Math.max(1,Math.min(9,f.adults));s.childAges=f.ages.slice();pendingFamily=null;refresh();return f;}if(f.count===0&&s){if(f.adults)s.adults=Math.max(1,Math.min(9,f.adults));s.childAges=[];pendingFamily=null;refresh();return f;}pendingFamily={...f,sourceText:String(text||''),createdAt:Date.now()};return f;}
function decorate(){const root=document.getElementById('noreyoAi556Result'),card=root?.querySelector('.noreyo-v556-result');if(!card)return;card.querySelectorAll('[data-noreyo-v572-family]').forEach(x=>x.remove());const f=parseFamily(aiText());if(!f)return;const b=document.createElement('div');b.dataset.noreyoV572Family='1';if(f.complete){b.className='noreyo-v556-group';const a=f.adults?`${f.adults} ${f.adults===1?'Erwachsener':'Erwachsene'} · `:'';const c=f.count?`${f.count} ${f.count===1?'Kind':'Kinder'} · Alter ${f.ages.join(' / ')}`:'ohne Kinder';b.innerHTML='<p class="noreyo-v556-grouplabel">Reisende</p><div class="noreyo-v556-chips"><span class="noreyo-v556-chip"><i>✓</i>'+a+c+'</span></div>';}else{b.className='noreyo-v556-open';b.innerHTML='<b>Kinderalter noch offen:</b> '+f.errors.join(' · ')+'. Bitte ergänze die Reisenden vor der Suche.';}const anchor=card.querySelector('.noreyo-v556-safe,.noreyo-v556-actions');anchor?card.insertBefore(b,anchor):card.appendChild(b);}
function travellersValid(){const s=state();if(!s)return false;const adults=Math.round(Number(s.adults)),ages=Array.isArray(s.childAges)?s.childAges.map(Number):[];return Number.isInteger(adults)&&adults>=1&&adults<=9&&adults+ages.length<=9&&ages.every(v=>Number.isInteger(v)&&v>=0&&v<=17)&&ages.filter(v=>v<=1).length<=adults;}
function openTravellers(){try{if(typeof openPlanner==='function'){plannerRequested=true;openPlanner('travellers');return true;}}catch(_){}for(const q of ['.travellerInput','.travelerInput','[data-planner="travellers"]','[data-field="travellers"]']){const el=document.querySelector(q);if(el){plannerRequested=true;el.click();return true;}}return false;}
function notify(msg){try{if(typeof showToast==='function')showToast(msg);else if(typeof toast==='function')toast(msg);}catch(_){}}
function onApplyCapture(e){const btn=e.target instanceof Element?e.target.closest('.noreyo-v556-apply'):null;if(!btn)return;const text=aiText(),s=state();adultSnapshot=!explicitAdults(text)&&Number.isInteger(Math.round(Number(s?.adults)))?Math.round(Number(s.adults)):null;setTimeout(()=>{apply(text);if(adultSnapshot&&s&&Math.round(Number(s.adults))!==adultSnapshot){s.adults=adultSnapshot;refresh();}adultSnapshot=null;decorate();},0);}
function blockSearch(e){if(!pendingFamily)return;const target=e.target instanceof Element?e.target.closest('.liveSearchButton,.noreyo-v541-booking-cta'):null;if(!target)return;e.preventDefault();e.stopImmediatePropagation();notify(pendingFamily.errors[0]||'Bitte ergänze die Kinderalter.');setTimeout(openTravellers,0);}
function onAnalyze(e){if(e.target instanceof Element&&e.target.closest('.noreyo-v556-analyze')){pendingFamily=null;plannerRequested=false;setTimeout(decorate,0);}}
function onPlannerSave(e){if(!pendingFamily||!plannerRequested||!(e.target instanceof Element))return;if(!e.target.closest('.planner-save,.planner-apply,[data-planner-apply]'))return;setTimeout(()=>{if(travellersValid()){pendingFamily=null;plannerRequested=false;}},0);}
function install(){window.addEventListener('click',blockSearch,true);document.addEventListener('click',onApplyCapture,true);document.addEventListener('click',onAnalyze,true);document.addEventListener('click',onPlannerSave,true);}
window.NOREYO_V572=Object.freeze({BUILD,explicitAdults,parseAdults,noChildren,parseCount,parseAges,parseFamily,apply,travellersValid,get pendingFamily(){return pendingFamily;}});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();