/* NOREYO V5.83 — Travel DNA + Safari modal stability */
(function(){
'use strict';
const BUILD='5.83';
let activeDialog=null,returnFocus=null,ownedScrollY=null,lastDnaSig='';
const nativeRAF=window.requestAnimationFrame.bind(window);
function focusables(root){return [...root.querySelectorAll('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')].filter(el=>!el.hidden&&el.getClientRects().length);}
function visibleDialog(){return document.querySelector('#noreyoDna560.show .noreyo-v560-sheet,#noreyoFilter557.show .noreyo-v557-sheet,.noreyo-v556-backdrop.show .noreyo-v556-sheet,.planner-sheet.show,.sheet.show,[role="dialog"].show');}
function syncDialog(){const dialog=visibleDialog();if(dialog===activeDialog)return;if(!dialog){activeDialog=null;document.querySelector('.nav')?.classList.remove('noreyo-v583-nav-hidden');const el=returnFocus;returnFocus=null;if(el&&document.contains(el))setTimeout(()=>el.focus?.({preventScroll:true}),0);return;}if(!activeDialog)returnFocus=document.activeElement instanceof HTMLElement?document.activeElement:null;activeDialog=dialog;dialog.setAttribute('role','dialog');dialog.setAttribute('aria-modal','true');document.querySelector('.nav')?.classList.add('noreyo-v583-nav-hidden');const items=focusables(dialog);if(items.length&&!dialog.contains(document.activeElement))setTimeout(()=>items[0].focus?.({preventScroll:true}),0);}
function onKey(event){const dialog=activeDialog||visibleDialog();if(!dialog)return;if(event.key==='Escape'){const close=dialog.querySelector('.planner-close,.close,.noreyo-v560-close,.noreyo-v556-close,.noreyo-v557-close,[data-close],[data-close-cruise-sheet],button[aria-label*="schließ" i],button[aria-label*="close" i]');if(close){event.preventDefault();close.click();}return;}if(event.key!=='Tab')return;const items=focusables(dialog);if(!items.length)return;const first=items[0],last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}
function viewport(){const vv=window.visualViewport;const h=Math.max(320,Math.round(vv?.height||window.innerHeight||800));document.documentElement.style.setProperty('--noreyo-v583-vh',`${h}px`);document.body?.classList.toggle('noreyo-v583-keyboard',!!vv&&(window.innerHeight-vv.height>120));}
function ownsScroll(){return !!document.querySelector('#noreyoDna560.show .noreyo-v560-sheet,#noreyoFilter557.show .noreyo-v557-sheet');}
function restoreScroll(){if(ownedScrollY===null)return;const y=ownedScrollY;ownedScrollY=null;const b=document.body;if(b){b.style.position='';b.style.top='';b.style.left='';b.style.right='';b.style.width='';}try{window.scrollTo({top:y,left:0,behavior:'auto'});}catch(_){window.scrollTo(0,y);}}
function syncScroll(){if(!ownsScroll()){restoreScroll();return;}if(ownedScrollY!==null)return;ownedScrollY=Math.max(0,window.scrollY||0);const b=document.body;if(!b)return;b.style.position='fixed';b.style.top=`-${ownedScrollY}px`;b.style.left='0';b.style.right='0';b.style.width='100%';}
function dnaSignature(){const intro=document.querySelector('#noreyoDnaBody .noreyo-v566-intro');if(!intro)return'';return [intro.className,intro.querySelector('h3,.noreyo-v566-title')?.textContent||'',intro.querySelector('.noreyo-v563-start-note')?.textContent||'',intro.querySelector('.noreyo-v560-photo small')?.textContent||''].join('|');}
function installDnaLoopGuard(){window.requestAnimationFrame=function(cb){if(cb&&cb.name==='polishIntro'&&document.querySelector('#noreyoDnaBody .noreyo-v566-intro')){const sig=dnaSignature();if(sig&&sig===lastDnaSig)return nativeRAF(()=>{});lastDnaSig=sig;}return nativeRAF(cb);};}
function style(){if(document.getElementById('noreyoV583Style'))return;const s=document.createElement('style');s.id='noreyoV583Style';s.textContent='@media(max-width:600px){.noreyo-v583-nav-hidden,.noreyo-v583-keyboard .nav{visibility:hidden!important;pointer-events:none!important}.noreyo-v560-close,.noreyo-v557-close,.noreyo-v556-close,[data-close-cruise-sheet]{min-width:44px!important;min-height:44px!important;touch-action:manipulation}.noreyo-v557-sheet,.noreyo-v556-sheet,.noreyo-v560-sheet,.planner-sheet,.sheet{max-height:calc(var(--noreyo-v583-vh,100vh) - 10px)!important}.noreyo-v560-launch-copy b{font-size:13.5px!important}.noreyo-v560-launch-copy em,.noreyo-v560-privacy,.noreyo-v563-start-note,.noreyo-v560-choice-copy small,.noreyo-v563-profile-rows>span{font-size:10.5px!important;line-height:1.35!important}.noreyo-v557-copy,.noreyo-v557-item-copy b{font-size:13px!important}.noreyo-v557-item{min-height:54px!important}.noreyo-v557-foot button{height:48px!important}}@media(max-width:360px){.noreyo-v560-body,.noreyo-v557-body{padding-left:14px!important;padding-right:14px!important}}@media(prefers-reduced-motion:reduce){.noreyo-v557-sheet,.noreyo-v556-sheet,.noreyo-v560-sheet,.planner-sheet,.sheet{transition:none!important;animation:none!important}}';document.head.appendChild(s);}
function lifecycle(){restoreScroll();viewport();syncDialog();syncScroll();}
function install(){installDnaLoopGuard();style();viewport();syncDialog();syncScroll();document.addEventListener('keydown',onKey,true);window.visualViewport?.addEventListener('resize',viewport,{passive:true});window.visualViewport?.addEventListener('scroll',viewport,{passive:true});window.addEventListener('pagehide',restoreScroll,{passive:true});window.addEventListener('pageshow',lifecycle,{passive:true});if(typeof MutationObserver!=='undefined')new MutationObserver(()=>{syncDialog();syncScroll();}).observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});}
window.NOREYO_V583=Object.freeze({BUILD,visibleDialog,dnaSignature,restoreScroll});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
