/* NOREYO V9.18 — serialize hotel/package searches and keep only the latest queued intent. */
(function(){
'use strict';
const BUILD='9.18';let installed=false,active=null,activeSig='',pending=null;
function signature(){try{const s=typeof searchState!=='undefined'?searchState:{},st=typeof states!=='undefined'?states:{};return JSON.stringify({mode:typeof productMode!=='undefined'?productMode:'',dest:typeof dest!=='undefined'?dest:'',hotel:typeof hotelQuery!=='undefined'?hotelQuery:'',airports:Array.isArray(s?.airports)?s.airports:[],checkin:s?.checkin||'',checkout:s?.checkout||'',adults:s?.adults||0,children:Array.isArray(s?.childAges)?s.childAges:[],meal:typeof mealPlanFilter!=='undefined'?mealPlanFilter:'',states:Object.keys(st||{}).sort().map(k=>[k,st[k]])});}catch(_){return String(Date.now());}}
function isFlightMode(){try{return String(productMode||'')==='flight';}catch(_){return false;}}
function settleAndDrain(){active=null;activeSig='';const next=pending;pending=null;if(next)queueMicrotask(()=>launch(next));}
function launch(job){const prior=window.searchTrips?.__noreyoV918Prior||window.searchTrips;if(typeof prior!=='function'){job.reject?.(new Error('searchTrips unavailable'));return null;}activeSig=job.sig;let result;try{result=Promise.resolve(prior.apply(job.thisArg,job.args));}catch(error){result=Promise.reject(error);}active=result.then(v=>{job.resolve?.(v);return v},e=>{job.reject?.(e);throw e}).finally(settleAndDrain);active.catch(()=>{});return job.promise||active;}
function install(){if(installed||typeof window.searchTrips!=='function'||window.searchTrips.__noreyoV918)return false;const prior=window.searchTrips;const wrapped=function(...args){if(isFlightMode())return prior.apply(this,args);const sig=signature();if(!active){return launch({thisArg:this,args,sig});}if(sig===activeSig)return active;if(pending&&pending.sig===sig)return pending.promise;let resolve,reject;const promise=new Promise((res,rej)=>{resolve=res;reject=rej});pending={thisArg:this,args,sig,promise,resolve,reject};return promise;};wrapped.__noreyoV918=true;wrapped.__noreyoV918Prior=prior;window.searchTrips=wrapped;installed=true;return true;}
install();window.addEventListener('pageshow',install,{passive:true});window.NOREYO_V918=Object.freeze({BUILD,signature,isFlightMode,install,getState:()=>({active:!!active,activeSig,pendingSig:pending?.sig||''})});
})();