/* NOREYO V6.73 — async-safe match ranking + latest-only detail decoration. */
(function(){
'use strict';
const BUILD='6.73';
let detailSeq=0;
if(!document.querySelector('link[data-noreyo-v534]')){const link=document.createElement('link');link.rel='stylesheet';link.href='./noreyo-v534.css?build=534';link.dataset.noreyoV534='1';document.head.appendChild(link);}
const checks=[['Zimmer0','Balkon',o=>o.confirmed?.balcony===true],['Zimmer1','Meerblick',o=>o.confirmed?.seaView===true],['Zimmer2','Terrasse',o=>o.confirmed?.terrace===true],['Hotel0','4★+',o=>Number(o.stars||0)>=4],['Hotel4','Spa',o=>o.confirmed?.spa===true],['Hotel5','Fitness',o=>o.confirmed?.fitness===true],['Hotel6','Frühstück',o=>o.confirmed?.breakfast===true],['Hotel7','All Inclusive',o=>o.confirmed?.allInclusive===true],['Preis2','Stornierbar',o=>o.refundable===true]];
function mealCode(board){try{if(window.NOREYO_V548?.codeFromBoard)return String(window.NOREYO_V548.codeFromBoard(board)||'ANY').toUpperCase();}catch(_){ }const b=String(board||'').toLowerCase();if(/all\s*[- ]?inclusive|\bai\d*\b|\bti\b/.test(b))return'AI';if(/vollpension|full\s*board|\bfb\d*\b/.test(b))return'FB';if(/halbpension|half\s*board|\bhb\d*\b|\bbd\b/.test(b))return'HB';if(/frühstück|fruhstuck|breakfast|\bbb\d*\b|\bbi\b/.test(b))return'BB';if(/nur\s*übernachtung|nur\s*ubernachtung|room\s*only|\bro\d*\b/.test(b))return'RO';return'ANY';}
function mealMatches(o){const wanted=String(mealPlanFilter||'ANY').toUpperCase();return wanted==='ANY'||mealCode(o?.board)===wanted;}
function matchData(o){let points=0;const items=[];for(const [key,label,test] of checks){const state=states[key]||'any';if(state==='any')continue;const ok=!!test(o);if(ok)points+=state==='must'?6:2;items.push({label,state,ok});}if(mealPlanFilter&&mealPlanFilter!=='ANY'){const ok=mealMatches(o);if(ok)points+=6;items.push({label:mealPlanLabel(),state:'must',ok});}return{points,items,confirmed:items.filter(x=>x.ok).length,active:items.length};}
function detailMatchLabel(m){if(!m.active)return'LIVE';if(m.confirmed>=4)return'SEHR PASSEND';if(m.confirmed>=2)return'GUT PASSEND';return'PASSEND';}
function preferenceCounts(){return{must:Object.values(states).filter(x=>x==='must').length,wish:Object.values(states).filter(x=>x==='wish').length};}
function decorateSearch(){document.querySelectorAll('#discover .search-card,#searchView .search-card').forEach(card=>{const head=card.querySelector('.search-console-head'),old=card.querySelector('.noreyo-search-logic');if(productMode==='flight'||!head){old?.remove();return;}if(old)return;head.insertAdjacentHTML('afterend','<div class="noreyo-search-logic" aria-label="So priorisiert NOREYO deine Wünsche"><div><span class="noreyo-logic-tag must">MUSS</span><b>wird strikt geprüft</b></div><span class="noreyo-logic-arrow">→</span><div><span class="noreyo-logic-tag wish">WUNSCH</span><b>verbessert deinen Match</b></div></div>');});}
function decorateResultPrinciple(){const anchor=document.querySelector('#results .match');if(!anchor)return;const counts=preferenceCounts();let box=document.querySelector('#results .noreyo-results-principle');if(!box){anchor.insertAdjacentHTML('afterend','<div class="noreyo-results-principle"></div>');box=document.querySelector('#results .noreyo-results-principle');}const title=(counts.must||counts.wish)?`${counts.must} Pflicht · ${counts.wish} ${counts.wish===1?'Wunsch':'Wünsche'}`:'Noch keine Prioritäten gesetzt';const copy=(counts.must||counts.wish)?'Pflichtkriterien werden strikt geprüft. Danach zählt jede bestätigte Wunsch-Übereinstimmung für dein persönliches Ranking.':'Setze Wünsche oder Pflichtkriterien – dann wird aus einer normalen Hotelsuche dein persönliches Ranking.';box.innerHTML=`<div><span>NOREYO PRIORITÄTEN</span><strong>${safeText(title)}</strong></div><p>${safeText(copy)}</p>`;}
function decorateOffers(){document.querySelectorAll('#offers .offer').forEach(card=>{card.classList.add('noreyo-offer');const img=card.querySelector('.offer-img');if(img){let badge=img.querySelector('.noreyo-match-badge');if(!badge){img.insertAdjacentHTML('beforeend','<div class="noreyo-match-badge"><span>NOREYO MATCH</span><strong>WIRD GEPRÜFT</strong><small>Hotelmerkmale werden sicher zugeordnet</small></div>');badge=img.querySelector('.noreyo-match-badge');}if(badge)badge.dataset.noreyoNeutral='1';}const line=card.querySelector('.offer-matchline');if(line&&!line.children.length)line.innerHTML='<span class="offer-matchchip neutral">Tarifdaten werden geprüft</span>';card.querySelector('.offer-essentials')?.classList.add('noreyo-essentials');card.querySelector('.offer-price-context')?.classList.add('noreyo-price-panel');const btn=card.querySelector('.dark-btn');if(btn){btn.classList.add('noreyo-cta');btn.innerHTML=`Hotel & Tarife ansehen ${svg('chev')}`;let trust=card.querySelector('.noreyo-trust-row');if(!trust){btn.insertAdjacentHTML('beforebegin','<div class="noreyo-trust-row"><span><i></i>Tarifdaten verfügbar</span></div>');trust=card.querySelector('.noreyo-trust-row');}if(trust)trust.dataset.noreyoNeutral='1';}});decorateResultPrinciple();}
function detailMatchCopy(m){if(!m.active)return'Aktiviere Wünsche oder Pflichtkriterien – NOREYO erklärt dir danach für jedes Hotel, warum es zu dir passt.';const must=m.items.filter(x=>x.state==='must'),wishOk=m.items.filter(x=>x.state==='wish'&&x.ok).length,mustOk=must.filter(x=>x.ok).length;if(must.length&&mustOk===must.length&&wishOk)return`Alle ${must.length} Pflichtkriterien bestätigt · zusätzlich ${wishOk} ${wishOk===1?'Wunsch':'Wünsche'} durch Hoteldaten bestätigt.`;if(must.length&&mustOk===must.length)return`Alle ${must.length} Pflichtkriterien bestätigt. NOREYO wertet nur zusätzlich bestätigte Wünsche positiv.`;if(wishOk)return`${wishOk} ${wishOk===1?'deiner Wünsche ist':'deiner Wünsche sind'} durch vorhandene Hoteldaten bestätigt.`;return'NOREYO wertet nur Merkmale als Treffer, die sich mit den vorhandenen Hotel- und Tarifdaten tatsächlich bestätigen lassen.';}
function decorateDetail(o){const root=document.getElementById('detailContent');if(!root)return;root.querySelector('.noreyo-detail-match')?.remove();const rating=root.querySelector('.detail-rating');if(!rating)return;const m=matchData(o),confirmed=m.items.filter(x=>x.ok),chips=confirmed.slice(0,5).map(x=>`<span class="noreyo-detail-chip ${x.state}">${x.state==='must'?'Pflicht':'Wunsch'} · ${safeText(x.label)} ✓</span>`).join('');rating.insertAdjacentHTML('afterend',`<section class="noreyo-detail-match"><div class="noreyo-detail-score"><span>DEIN NOREYO MATCH</span><strong>${safeText(detailMatchLabel(m))}</strong></div><div class="noreyo-detail-why"><b>Warum passt dieses Hotel zu dir?</b><p>${safeText(detailMatchCopy(m))}</p></div>${chips?`<div class="noreyo-detail-chips">${chips}</div>`:''}</section>`);}
function afterResult(result,after){if(result&&typeof result.then==='function')return result.then(value=>{after();return value;});after();return result;}
function rankRows(out){if(!Array.isArray(out))return out;out.sort((a,b)=>matchData(b).points-matchData(a).points||Number(String(b.rating||0).replace(',','.'))-Number(String(a.rating||0).replace(',','.'))||Number(a.price||Infinity)-Number(b.price||Infinity));return out;}
const baseRender=renderOffers;renderOffers=function(){const r=baseRender.apply(this,arguments);return afterResult(r,decorateOffers);};
const baseFilter=filterAndRankOffers;filterAndRankOffers=function(){const r=baseFilter.apply(this,arguments);return r&&typeof r.then==='function'?r.then(rankRows):rankRows(r);};
const baseDetail=renderDetail;renderDetail=function(o){const seq=++detailSeq,r=baseDetail.apply(this,arguments);return afterResult(r,()=>{if(seq===detailSeq)decorateDetail(o);});};
const baseControls=renderProductControls;renderProductControls=function(){const r=baseControls.apply(this,arguments);return afterResult(r,decorateSearch);};
const baseCounts=updateCounts;updateCounts=function(){const r=baseCounts.apply(this,arguments);return afterResult(r,()=>{decorateSearch();decorateResultPrinciple();});};
window.addEventListener('pagehide',()=>{detailSeq++;},{passive:true});decorateSearch();decorateOffers();decorateResultPrinciple();
window.NOREYO_V533=Object.freeze({BUILD,decorateOffers,decorateDetail,matchData,mealCode,mealMatches,afterResult,rankRows,get detailSeq(){return detailSeq;}});
})();