/* NOREYO V10.36 — retire obsolete V9.04 flight-preference downgrade.
   V9.04 predates the conservative V10.x flight-truth layers. It still migrates
   every Flug*=must to wish and disables MUST/maxFlightMinutes. This layer loads
   before the legacy stack, snapshots persisted flight preferences, then retires
   V9.04 and restores that snapshot once the real state exists. */
(function(){
'use strict';
const BUILD='10.36',NOTE_ID='noreyo-v1036-flight-note',STORAGE_KEYS=['oneTripV52','oneTripV51','oneTripV5'];
let observer=null,raf=0,pollTimer=0,pollStarted=0,retired=false,restored=false;
function persistedFlightPrefs(){try{for(const key of STORAGE_KEYS){const raw=localStorage.getItem(key);if(!raw)continue;const parsed=JSON.parse(raw),src=parsed?.states;if(!src||typeof src!=='object')continue;const out={};for(const [k,v] of Object.entries(src))if(/^Flug\d+$/.test(k)&&['any','wish','must'].includes(v))out[k]=v;return out;}}catch(_){}return{};}
const captured=Object.freeze({...persistedFlightPrefs()});
function stateObj(){try{return typeof states!=='undefined'&&states?states:(window.states||null);}catch(_){return window.states||null;}}
function restoreCaptured(){if(restored)return false;const s=stateObj(),entries=Object.entries(captured);if(!s||!entries.length)return false;let changed=false;for(const [k,v] of entries)if(s[k]!==v){s[k]=v;changed=true;}restored=true;if(changed){try{persistState?.();}catch(_){}try{updateCounts?.();}catch(_){}try{refreshQuickStates?.();}catch(_){}}return changed;}
function retireLegacy(){const old=window.NOREYO_V904;if(!old)return false;let changed=false;try{old.cleanup?.();changed=true;}catch(_){}try{window.removeEventListener('pageshow',old.observe);}catch(_){}try{window.removeEventListener('pagehide',old.cleanup);}catch(_){}retired=true;restoreCaptured();return changed;}
function activeFlight(){try{return typeof activeTab!=='undefined'&&activeTab==='Flug';}catch(_){return false;}}
function enableControls(root=document.getElementById('sheetScroll')){if(!root||!activeFlight())return false;let changed=false;root.querySelectorAll?.('.pref .seg button.must').forEach(btn=>{if(btn.disabled){btn.disabled=false;changed=true;}if(btn.getAttribute('aria-disabled')==='true'){btn.setAttribute('aria-disabled','false');changed=true;}if(btn.title==='Noch nicht als harter Flugfilter verfügbar'){btn.removeAttribute('title');changed=true;}});const range=[...root.querySelectorAll?.('.range')||[]].find(x=>/Maximale Flugzeit/i.test(x.textContent||''));if(range){const input=range.querySelector('input[type="range"]');if(input?.disabled){input.disabled=false;changed=true;}if(input?.getAttribute('aria-disabled')==='true'){input.setAttribute('aria-disabled','false');changed=true;}const hint=range.querySelector('.filter-hint');const text='Harte Grenze: Solange die aktuelle Flight-Normalisierung die Dauer nicht sicher bestätigt, wird die Angebotsauswahl konservativ gesperrt.';if(hint&&hint.textContent!==text){hint.textContent=text;changed=true;}}const stale=root.querySelector('#noreyo-v904-flight-note');if(stale){stale.remove();changed=true;}let note=root.querySelector('#'+NOTE_ID);if(!note){note=document.createElement('div');note.id=NOTE_ID;note.className='filter-hint';note.setAttribute('role','note');const intro=root.querySelector('.sheet-intro');(intro?.parentNode||root).insertBefore(note,intro?.nextSibling||root.firstChild);changed=true;}const txt='Flug-Pflichtkriterien sind aktiv. Kann NOREYO ein Pflichtmerkmal in den aktuellen Providerdaten nicht sicher bestätigen, bleibt das Angebot sichtbar, aber nicht auswählbar.';if(note.textContent!==txt){note.textContent=txt;changed=true;}return changed;}
function run(){raf=0;retireLegacy();restoreCaptured();enableControls();}
function schedule(){if(!raf)raf=requestAnimationFrame(run);}
function observe(){if(observer){observer.disconnect();observer=null;}if(typeof MutationObserver==='undefined'||!document.body)return false;observer=new MutationObserver(schedule);observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class','disabled']});schedule();return true;}
function startPoll(){if(pollTimer||retired)return false;pollStarted=Date.now();pollTimer=setInterval(()=>{if(retireLegacy()){clearInterval(pollTimer);pollTimer=0;observe();schedule();return;}if(Date.now()-pollStarted>45000){clearInterval(pollTimer);pollTimer=0;}},50);return true;}
function cleanup(){if(observer){observer.disconnect();observer=null;}if(raf){cancelAnimationFrame(raf);raf=0;}if(pollTimer){clearInterval(pollTimer);pollTimer=0;}}
observe();startPoll();window.addEventListener('pagehide',cleanup,{passive:true});window.addEventListener('pageshow',()=>{observe();startPoll();},{passive:true});
window.NOREYO_V1036=Object.freeze({BUILD,NOTE_ID,STORAGE_KEYS,captured,persistedFlightPrefs,stateObj,restoreCaptured,retireLegacy,activeFlight,enableControls,run,schedule,observe,startPoll,cleanup,status:()=>({retired,restored,polling:!!pollTimer})});
})();