/* NOREYO V7.53 — context-aware departure-airport AI parsing.
   Expands useful departure coverage and prevents destination mentions such as
   "nach Düsseldorf" from being misread as departure airports. */
(function(){
'use strict';
const BUILD='7.53';
const defs=[['DUS',['duesseldorf','dusseldorf','dus']],['CGN',['koeln/bonn','koln/bonn','koeln','koln','cgn']],['PAD',['paderborn','pad']],['FMO',['muenster/osnabrueck','munster/osnabruck','muenster','munster','fmo']],['FRA',['frankfurt','fra']],['HAJ',['hannover','haj']],['DTM',['dortmund','dtm']],['HAM',['hamburg','ham']],['MUC',['muenchen','munchen','muc']],['BER',['berlin','ber']],['STR',['stuttgart','str']],['NUE',['nuernberg','nurnberg','nue']],['LEJ',['leipzig/halle','leipzig','halle','lej']],['BRE',['bremen','bre']],['DRS',['dresden','drs']],['ERF',['erfurt','erf']],['SCN',['saarbruecken','saarbrucken','scn']],['FKB',['karlsruhe/baden-baden','baden-baden','karlsruhe','fkb']],['FMM',['memmingen','fmm']],['NRN',['weeze','niederrhein','nrn']],['KSF',['kassel','ksf']],['FDH',['friedrichshafen','fdh']],['SZG',['salzburg','szg']],['BSL',['basel','bsl']],['ZRH',['zuerich','zurich','zrh']],['AMS',['amsterdam','ams']]];
function norm(v){return String(v||'').toLowerCase().replace(/ä/g,'ae').replace(/ö/g,'oe').replace(/ü/g,'ue').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').replace(/\s+/g,' ').trim();}
function escRe(v){return String(v).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');}
function airportHits(text){const t=norm(text),hits=[];for(const [code,names] of defs){for(const name of names){const re=new RegExp('(^|[^a-z0-9])('+escRe(name)+')([^a-z0-9]|$)','g');let m;while((m=re.exec(t))){const index=(m.index||0)+m[1].length;hits.push({code,name,index,end:index+m[2].length});}}}return hits.sort((a,b)=>a.index-b.index||b.name.length-a.name.length);}
function isIataAlias(hit){return hit.name===hit.code.toLowerCase();}
function departureCueBefore(t,index){const before=t.slice(Math.max(0,index-36),index);return /(?:^|\s)(?:ab|von|abflug(?:hafen)?|start(?:en)?\s+ab|fliegen\s+ab|flug\s+ab|departure\s+from)\s+(?:[a-z/-]+\s*(?:,|\/|oder|und)\s*)*$/i.test(before);}
function connectedToDeparture(t,hit,accepted){if(departureCueBefore(t,hit.index))return true;if(isIataAlias(hit)){const before=t.slice(Math.max(0,hit.index-8),hit.index);if(/\b(?:ab|von)\s*$/i.test(before))return true;}if(!accepted.length)return false;const prev=accepted[accepted.length-1],between=t.slice(prev.end,hit.index);return /^\s*(?:,|\/|\+|\bund\b|\boder\b)\s*$/i.test(between);}
function parseDepartures(text){const t=norm(text),out=[],accepted=[];for(const hit of airportHits(t)){if(out.includes(hit.code))continue;if(!connectedToDeparture(t,hit,accepted))continue;out.push(hit.code);accepted.push(hit);}return out;}
function mentionsDeparture(text){const t=norm(text);return /\b(?:ab|von|abflug(?:hafen)?|start(?:en)?\s+ab|fliegen\s+ab|flug\s+ab)\b/.test(t);}
function repairAnalysis(text){const codes=parseDepartures(text),root=document.getElementById('noreyoAi556Result');if(!root||!mentionsDeparture(text))return false;const groups=[...root.querySelectorAll('.noreyo-v556-group')];let travel=groups.find(g=>/reise/i.test(g.querySelector('.noreyo-v556-grouplabel')?.textContent||''));if(!travel)return false;const chips=travel.querySelector('.noreyo-v556-chips');if(!chips)return false;[...chips.querySelectorAll('.noreyo-v556-chip')].forEach(chip=>{if(/^Abflug\s*·/i.test(String(chip.textContent||'').replace(/^✓\s*/,'')))chip.remove();});if(codes.length){const chip=document.createElement('span');chip.className='noreyo-v556-chip';chip.innerHTML='<i>✓</i>Abflug · '+codes.join(' / ');chips.appendChild(chip);}const open=root.querySelector('.noreyo-v556-open');if(open&&codes.length&&/Abflughafen/i.test(open.textContent||'')){const m=String(open.textContent||'').match(/Noch offen:\s*(.*?)\.\s*Du kannst/i),parts=(m?.[1]||'').split('·').map(x=>x.trim()).filter(x=>x&&!/^Abflughafen$/i.test(x));if(!parts.length)open.remove();else open.innerHTML='<b>Noch offen:</b> '+parts.join(' · ')+'. Du kannst das anschließend in der normalen Suche ergänzen.';}return true;}
function apply(text){if(!mentionsDeparture(text))return false;const codes=parseDepartures(text);if(!codes.length)return false;try{if(typeof searchState==='undefined'||!searchState)return false;const old=Array.isArray(searchState.airports)?searchState.airports.map(String):[];if(old.length===codes.length&&old.every((v,i)=>v===codes[i]))return false;searchState.airports=codes.slice();try{updateSearchUI?.();}catch(_){}try{persistState?.();}catch(_){}return true;}catch(_){return false;}}
function inputText(){return document.getElementById('noreyoAi556Text')?.value||'';}
function onAnalyze(e){if(!e.target?.closest?.('.noreyo-v556-analyze'))return;const text=inputText();setTimeout(()=>repairAnalysis(text),160);}
function onApply(e){if(!e.target?.closest?.('.noreyo-v556-apply'))return;const text=inputText();setTimeout(()=>setTimeout(()=>apply(text),0),0);}
document.addEventListener('click',onAnalyze,true);document.addEventListener('click',onApply,true);
window.NOREYO_V753=Object.freeze({BUILD,norm,airportHits,departureCueBefore,connectedToDeparture,parseDepartures,mentionsDeparture,repairAnalysis,apply});
})();