/* NOREYO V10.84 — server-side live flight verify step.
   Adds the first real post-selection checkout step without exposing provider secrets.
   Selected offers are verified through Supabase /functions/v1/flight-verify; a verified
   snapshot stays in memory only and is invalidated whenever the selected offer changes. */
(function(){
'use strict';
const BUILD='10.84';
const ENDPOINT='https://fcvffslhnaqlwitaeers.supabase.co/functions/v1/flight-verify';
const VERIFY_TIMEOUT_MS=20000;
let observer=null,raf=0,inflight=null,lastSelectedId='';
function selected(){return window.NOREYO_SELECTED_FLIGHT||null;}
function offerId(){return String(selected()?.offerId||'').trim();}
function anon(){try{return typeof anonKey!=='undefined'?String(anonKey||''):'';}catch(_){return'';}}
function verification(){return window.NOREYO_VERIFIED_FLIGHT||null;}
function clearVerification(){if(!verification())return false;try{delete window.NOREYO_VERIFIED_FLIGHT;}catch(_){window.NOREYO_VERIFIED_FLIGHT=undefined;}return true;}
function sameOffer(){const v=verification(),id=offerId();return !!v&&!!id&&v.offerId===id;}
function finite(v){const n=Number(v);return Number.isFinite(n)&&n>=0?n:null;}
function firstFinite(...values){for(const v of values){const n=finite(v);if(n!==null)return n;}return null;}
function price(payload){return firstFinite(payload?.pricing?.display?.total,payload?.pricing?.display?.totalAmount,payload?.pricing?.display?.amount,payload?.data?.pricing?.display?.total,payload?.data?.pricing?.display?.totalAmount,payload?.offer?.pricing?.display?.total,payload?.offer?.pricing?.display?.totalAmount,payload?.journey?.pricing?.display?.total,payload?.journey?.pricing?.display?.totalAmount);}
function currency(payload){return String(payload?.pricing?.display?.currency||payload?.data?.pricing?.display?.currency||payload?.offer?.pricing?.display?.currency||payload?.journey?.pricing?.display?.currency||selected()?.currency||'EUR').trim().toUpperCase().slice(0,3)||'EUR';}
function changes(payload){return payload?.changes||payload?.data?.changes||payload?.offer?.changes||null;}
function hasChanges(payload){const c=changes(payload);if(!c)return false;if(Array.isArray(c))return c.length>0;if(typeof c==='object')return Object.keys(c).length>0;return !!c;}
function money(value,cur='EUR'){if(value===null)return'Preis live verifiziert';try{return new Intl.NumberFormat('de-DE',{style:'currency',currency:/^[A-Z]{3}$/.test(cur)?cur:'EUR',maximumFractionDigits:2}).format(value);}catch(_){return `${value} ${cur}`;}}
function messageFrom(payload,status){if(status===404)return'Dieses Flugangebot ist abgelaufen. Bitte suche erneut.';return String(payload?.error?.message||payload?.message||`Flugangebot konnte nicht verifiziert werden (HTTP ${status}).`);}
async function verify(){const id=offerId();if(!id)throw new Error('Kein Flugangebot ausgewählt.');const key=anon();if(!key)throw new Error('NOREYO konnte die sichere Verify-Verbindung nicht initialisieren.');if(inflight?.offerId===id)return inflight.promise;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),VERIFY_TIMEOUT_MS);const promise=(async()=>{try{const response=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','apikey':key,'Authorization':`Bearer ${key}`},body:JSON.stringify({offerId:id}),signal:controller.signal});let payload={};try{payload=await response.json();}catch(_){}if(!response.ok)throw Object.assign(new Error(messageFrom(payload,response.status)),{status:response.status,payload});if(offerId()!==id)throw Object.assign(new Error('Die Flugauswahl hat sich während der Prüfung geändert.'),{code:'STALE_SELECTION'});const snapshot=Object.freeze({offerId:id,verifiedAt:new Date().toISOString(),price:price(payload),currency:currency(payload),changed:hasChanges(payload),payload});window.NOREYO_VERIFIED_FLIGHT=snapshot;return snapshot;}finally{clearTimeout(timer);if(inflight?.offerId===id)inflight=null;}})();inflight={offerId:id,promise,controller};return promise;}
function host(){const body=document.getElementById('plannerBody');if(!body||!selected())return null;if(!body.querySelector('.noreyo-v943-back'))return null;return body;}
function renderVerified(root,snap){let box=root.querySelector('.noreyo-v1084-verify-state');if(!box){box=document.createElement('div');box.className='backend-note noreyo-v1084-verify-state';const back=root.querySelector('.noreyo-v943-back');root.insertBefore(box,back);}const changed=snap.changed?'<b>Preis oder Tarifdetails haben sich geändert</b><p>Bitte prüfe die aktualisierten Angaben vor dem nächsten Schritt.</p>':'<b>Flugangebot live verifiziert</b><p>Preis und Verfügbarkeit wurden gerade erneut beim Provider geprüft.</p>';box.innerHTML=`${changed}<strong style="display:block;margin-top:8px">${money(snap.price,snap.currency)}</strong><small>Verifiziert ${new Date(snap.verifiedAt).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}</small>`;const btn=root.querySelector('.noreyo-v1084-verify');if(btn){btn.disabled=false;btn.textContent='Erneut verifizieren';}}
function renderError(root,error){let box=root.querySelector('.noreyo-v1084-verify-state');if(!box){box=document.createElement('div');box.className='backend-note noreyo-v1084-verify-state';const back=root.querySelector('.noreyo-v943-back');root.insertBefore(box,back);}box.innerHTML=`<b>Live-Verify nicht abgeschlossen</b><p>${String(error?.message||error||'Unbekannter Fehler').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}</p>`;const btn=root.querySelector('.noreyo-v1084-verify');if(btn){btn.disabled=false;btn.textContent='Erneut verifizieren';}}
function enhance(){raf=0;const root=host(),id=offerId();if(!root||!id)return false;if(lastSelectedId&&lastSelectedId!==id)clearVerification();lastSelectedId=id;let changed=false;let btn=root.querySelector('.noreyo-v1084-verify');if(!btn){btn=document.createElement('button');btn.type='button';btn.className='dark-btn noreyo-v1084-verify';btn.textContent='Flugpreis jetzt live verifizieren';const back=root.querySelector('.noreyo-v943-back');root.insertBefore(btn,back);changed=true;}if(sameOffer())renderVerified(root,verification());return changed;}
async function onClick(e){const btn=e.target?.closest?.('.noreyo-v1084-verify');if(!btn)return;e.preventDefault();e.stopPropagation();const root=host();if(!root)return;btn.disabled=true;btn.textContent='Flugangebot wird verifiziert …';try{const snap=await verify();renderVerified(root,snap);}catch(error){if(error?.status===404){clearVerification();try{window.NOREYO_V1028?.clear?.();}catch(_){}}renderError(root,error);}}
function schedule(){if(!raf)raf=requestAnimationFrame(enhance);}
function observe(){if(observer){observer.disconnect();observer=null;}if(typeof MutationObserver==='undefined'||!document.body)return false;observer=new MutationObserver(schedule);observer.observe(document.body,{subtree:true,childList:true});document.addEventListener('click',onClick,true);schedule();return true;}
function cleanup(){if(observer){observer.disconnect();observer=null;}document.removeEventListener('click',onClick,true);if(raf){cancelAnimationFrame(raf);raf=0;}try{inflight?.controller?.abort?.();}catch(_){}inflight=null;}
observe();window.addEventListener('pagehide',cleanup,{passive:true});window.addEventListener('pageshow',observe,{passive:true});window.NOREYO_V1084=Object.freeze({BUILD,ENDPOINT,VERIFY_TIMEOUT_MS,selected,offerId,verification,clearVerification,sameOffer,finite,firstFinite,price,currency,changes,hasChanges,money,messageFrom,verify,host,renderVerified,renderError,enhance,schedule,observe,cleanup});
})();