/* NOREYO V9.43 — selectable multi-origin flight offers.
   Replaces the V9.41 aggregate-only UI with normalized, deduplicated selectable
   offer cards while keeping the search price explicitly unverified. */
(()=>{
'use strict';
const BUILD='9.43',MAX_ORIGINS=6,MAX_OFFERS=40,MAX_DEPTH=7;
let installed=false,prior=null,selected=null;
function validIata(v){return /^[A-Z]{3}$/.test(String(v||'').trim().toUpperCase())}
function origins(values){const out=[];for(const raw of Array.isArray(values)?values:[]){const code=String(raw||'').trim().toUpperCase();if(validIata(code)&&!out.includes(code))out.push(code);if(out.length>=MAX_ORIGINS)break}return out}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function finite(v){const n=Number(v);return Number.isFinite(n)&&n>=0?n:null}
function firstFinite(...values){for(const v of values){const n=finite(v);if(n!==null)return n}return null}
function priceOf(o){return firstFinite(o?.pricing?.display?.total,o?.pricing?.display?.totalAmount,o?.pricing?.display?.amount,o?.pricing?.total,o?.pricing?.totalAmount,o?.totalAmount,o?.totalPrice,o?.price?.total,o?.price?.amount,o?.amount,o?.price)}
function currencyOf(o){return String(o?.pricing?.display?.currency||o?.pricing?.currency||o?.currency||o?.price?.currency||'EUR').trim().toUpperCase().slice(0,3)||'EUR'}
function baggageOf(o){const b=o?.baggage||o?.fare?.baggage||o?.fareFamily?.baggage;if(!b)return null;if(typeof b?.included==='boolean')return b.included;if(typeof b?.included==='number')return b.included>0;if(typeof b?.included==='string')return !/^(?:false|no|none|0)$/i.test(b.included.trim());return null}
function expiryOf(o){const raw=o?.expiration||o?.expiresAt||o?.expiry||o?.expires;return raw?String(raw):''}
function cheapestOf(o){return o?.isCheapest===true||o?.cheapest===true}
function offerIdOf(o){return typeof o?.offerId==='string'&&o.offerId.trim()?o.offerId:''}
function collectOffers(payload){const out=[],seenObj=new Set();function walk(node,depth,context){if(!node||depth>MAX_DEPTH||out.length>=MAX_OFFERS)return;if(typeof node!=='object')return;if(seenObj.has(node))return;seenObj.add(node);if(Array.isArray(node)){for(const x of node)walk(x,depth+1,context);return}const next={...context};if(node.airline||node.airlineName||node.carrier)next.airline=node.airlineName||node.airline||node.carrier;if(node.duration||node.totalDuration)next.duration=node.duration||node.totalDuration;if(node.fareFamily?.name||node.fareFamilyName)next.fareFamily=node.fareFamily?.name||node.fareFamilyName;if(node.cabinClass||node.cabin)next.cabin=node.cabinClass||node.cabin;const offerId=offerIdOf(node);if(offerId)out.push({offerId,raw:node,context:next});for(const [k,v] of Object.entries(node)){if(k==='offerId'||k==='secretKey'||k==='token')continue;walk(v,depth+1,next)}}walk(payload,0,{});const dedup=[],ids=new Set();for(const x of out){if(ids.has(x.offerId))continue;ids.add(x.offerId);dedup.push(x)}return dedup.slice(0,MAX_OFFERS)}
function normalizeOffer(entry,origin,dest){const o=entry?.raw||{},ctx=entry?.context||{};return{offerId:entry.offerId,origin,destination:dest,price:priceOf(o),currency:currencyOf(o),expiration:expiryOf(o),baggageIncluded:baggageOf(o),isCheapest:cheapestOf(o),airline:String(ctx.airline||o.airlineName||o.airline||''),duration:String(ctx.duration||o.duration||''),fareFamily:String(ctx.fareFamily||o.fareFamily?.name||''),cabin:String(ctx.cabin||o.cabinClass||'')}}
function normalizedOffers(origin,dest,payload){return collectOffers(payload).map(x=>normalizeOffer(x,origin,dest))}
function sortOffers(list){return [...list].sort((a,b)=>{if(a.isCheapest!==b.isCheapest)return a.isCheapest?-1:1;const ap=a.price===null?Infinity:a.price,bp=b.price===null?Infinity:b.price;return ap-bp})}
function money(v,c='EUR'){return v===null?'Preis wird beim Prüfen bestätigt':new Intl.NumberFormat('de-DE',{style:'currency',currency:/^[A-Z]{3}$/.test(c)?c:'EUR',maximumFractionDigits:2}).format(v)}
function expiryLabel(v){if(!v)return'';const d=new Date(v);if(Number.isNaN(d.getTime()))return'';return `Angebot gültig bis ${d.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}`}
function offerCard(o,index){const baggage=o.baggageIncluded===true?'Gepäck laut Tarif enthalten':o.baggageIncluded===false?'Gepäck nicht enthalten':'Gepäck vor Buchung prüfen';const extras=[o.airline,o.fareFamily,o.cabin,o.duration].filter(Boolean).map(esc).join(' · ');return `<article class="flight-preview-card noreyo-v943-offer" data-flight-offer-index="${index}" style="margin-bottom:10px"><div class="flight-route"><div><span class="flight-code">${esc(o.origin)}</span><small>${esc(fmtDateLong(searchState.checkin))}</small></div><span class="flight-route-line">${svg('plane','icon mini')}</span><div style="text-align:right"><span class="flight-code">${esc(o.destination)}</span><small>${esc(fmtDateLong(searchState.checkout))} zurück</small></div></div><div class="flight-status">${o.isCheapest?'<span class="confirmed" style="margin:0 0 7px;display:inline-block">Günstigstes Angebot</span>':''}<b style="display:block;font-size:17px">${esc(money(o.price,o.currency))}</b>${extras?`<span style="display:block;margin-top:4px">${extras}</span>`:''}<span style="display:block;margin-top:5px">${esc(baggage)}</span>${expiryLabel(o.expiration)?`<small style="display:block;margin-top:5px">${esc(expiryLabel(o.expiration))}</small>`:''}<small style="display:block;margin-top:7px">Suchpreis noch unverifiziert · vor Checkout wird der Tarif erneut geprüft.</small></div><button type="button" class="dark-btn noreyo-v943-select" data-flight-offer-index="${index}">Angebot auswählen</button></article>`}
function selectionHTML(o){return `<div class="flight-preview"><div class="flight-preview-card"><div class="flight-route"><div><span class="flight-code">${esc(o.origin)}</span><small>${esc(fmtDateLong(searchState.checkin))}</small></div><span class="flight-route-line">${svg('plane','icon mini')}</span><div style="text-align:right"><span class="flight-code">${esc(o.destination)}</span><small>${esc(fmtDateLong(searchState.checkout))} zurück</small></div></div><div class="flight-status"><b>${esc(money(o.price,o.currency))}</b><br>Ausgewählt, aber noch nicht verifiziert. LiteAPI verlangt vor Prebook zwingend einen aktuellen Verify-Schritt.</div></div><div class="backend-note"><b>Nächster sicherer Schritt: Live-Verify</b><p>Der vollständige offerId bleibt nur in dieser Sitzung erhalten. NOREYO startet noch keine Zahlung oder Buchung, solange der serverseitige Verify/Prebook-Pfad nicht nachweislich verfügbar ist.</p></div><button type="button" class="ghost-btn noreyo-v943-back">Andere Flüge ansehen</button></div>`}
function render(body,dest,offers,failures){if(!body)return false;const sorted=sortOffers(offers).slice(0,MAX_OFFERS);body.__noreyoV943Offers=sorted;const fail=failures.length?`<div class="backend-note"><b>${failures.length} Abflughafen${failures.length===1?'':'/-häfen'} konnte${failures.length===1?'':'n'} nicht geprüft werden</b><p>${failures.map(x=>esc(x.origin)).join(', ')} · Auswahl bleibt erhalten.</p></div>`:'';if(!sorted.length){body.innerHTML=`<div class="flight-preview"><div class="flight-status"><b>Keine auswählbaren Flugangebote</b><br>${failures.length?'Mindestens eine Live-Abfrage ist fehlgeschlagen.':'Die Live-Suche war erreichbar, lieferte aber keine Angebote mit buchungsfähigem offerId.'}</div>${fail}<button type="button" class="dark-btn noreyo-v943-retry">Flüge erneut suchen</button></div>`;return true}body.innerHTML=`<div class="flight-preview"><div class="flight-status" style="margin:0 0 12px"><b>${sorted.length} auswählbare Flugangebote</b><br>Suchpreise sind live, aber bis zum Verify noch nicht garantiert.</div>${sorted.map(offerCard).join('')}${fail}</div>`;return true}
async function search(){const iata=destinationIata[String(dest).toLowerCase()];if(!iata){openPlanner('destination');showToast('Bitte zuerst ein Ziel wählen');return}const selectedOrigins=origins(searchState.airports);if(!selectedOrigins.length){openPlanner('airports');showToast('Bitte mindestens einen Abflughafen wählen');return}const base=flightRequestBody();openPlannerShell('Flüge',`<div class="loading-panel" style="margin:0"><span class="search-spinner"></span><b>${selectedOrigins.length} Abflughafen${selectedOrigins.length===1?'':'/-häfen'} werden geprüft</b><p>${selectedOrigins.map(esc).join(', ')} → ${esc(iata)}</p></div>`);const settled=await Promise.allSettled(selectedOrigins.map(async origin=>{const response=await window.NOREYO_V941.requestOrigin(origin,base);return{origin,offers:normalizedOffers(origin,iata,response.payload),payload:response.payload}}));const offers=[],failures=[];settled.forEach((s,i)=>s.status==='fulfilled'?offers.push(...s.value.offers):failures.push({origin:selectedOrigins[i],error:s.reason}));render(document.getElementById('plannerBody'),iata,offers,failures)}
function onClick(e){const body=document.getElementById('plannerBody');if(!body)return;const select=e.target?.closest?.('.noreyo-v943-select');if(select){const idx=Number(select.dataset.flightOfferIndex),offer=body.__noreyoV943Offers?.[idx];if(!offer)return;selected={...offer};window.NOREYO_SELECTED_FLIGHT=Object.freeze({...selected});body.innerHTML=selectionHTML(offer);return}if(e.target?.closest?.('.noreyo-v943-back')){search();return}if(e.target?.closest?.('.noreyo-v943-retry')){search();return}}
function install(){if(installed)return false;try{if(typeof searchFlights!=='function'||!window.NOREYO_V941?.requestOrigin)return false;prior=searchFlights;searchFlights=search;document.addEventListener('click',onClick,true);installed=true;return true}catch(_){return false}}
function restore(){if(!installed)return false;try{if(prior)searchFlights=prior;document.removeEventListener('click',onClick,true)}catch(_){}installed=false;return true}
install();window.NOREYO_V943=Object.freeze({BUILD,MAX_ORIGINS,MAX_OFFERS,validIata,origins,esc,finite,priceOf,currencyOf,baggageOf,expiryOf,cheapestOf,offerIdOf,collectOffers,normalizeOffer,normalizedOffers,sortOffers,money,expiryLabel,offerCard,selectionHTML,render,search,install,restore});
})();