/* NOREYO V8.00 — compound departure-airport disambiguation.
   Specific airport names such as Frankfurt-Hahn and Düsseldorf-Weeze win over
   overlapping city aliases, while ordinary multi-airport lists remain intact. */
(function(){
'use strict';
const BUILD='8.00';
const defs=[['HHN',['frankfurt-hahn','frankfurt hahn','hahn','hhn']],['NRN',['duesseldorf-weeze','dusseldorf-weeze','duesseldorf weeze','dusseldorf weeze','weeze','niederrhein','nrn']],['DUS',['duesseldorf','dusseldorf','dus']],['CGN',['koeln/bonn','koln/bonn','koeln','koln','cgn']],['PAD',['paderborn','pad']],['FMO',['muenster/osnabrueck','munster/osnabruck','muenster','munster','fmo']],['FRA',['frankfurt','fra']],['HAJ',['hannover','haj']],['DTM',['dortmund','dtm']],['HAM',['hamburg','ham']],['MUC',['muenchen','munchen','muc']],['BER',['berlin','ber']],['STR',['stuttgart','str']],['NUE',['nuernberg','nurnberg','nue']],['LEJ',['leipzig/halle','leipzig','halle','lej']],['BRE',['bremen','bre']],['DRS',['dresden','drs']],['ERF',['erfurt','erf']],['SCN',['saarbruecken','saarbrucken','scn']],['FKB',['karlsruhe/baden-baden','baden-baden','karlsruhe','fkb']],['FMM',['memmingen','fmm']],['KSF',['kassel','ksf']],['FDH',['friedrichshafen','fdh']],['SZG',['salzburg','szg']],['BSL',['basel','bsl']],['ZRH',['zuerich','zurich','zrh']],['AMS',['amsterdam','ams']]];
function norm(v){return String(v||'').toLowerCase().replace(/ä/g,'ae').replace(/ö/g,'oe').replace(/ü/g,'ue').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').replace(/\s+/g,' ').trim();}
function escRe(v){return String(v).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');}
function airportHits(text){const t=norm(text),hits=[];for(const [code,names] of defs){for(const name of names){const re=new RegExp('(^|[^a-z0-9])('+escRe(name)+')([^a-z0-9]|$)','g');let m;while((m=re.exec(t))){const index=(m.index||0)+m[1].length;hits.push({code,name,index,end:index+m[2].length});}}}return hits.sort((a,b)=>a.index-b.index||(b.end-b.index)-(a.end-a.index)||b.name.length-a.name.length);}
function overlaps(a,b){return a.index<b.end&&b.index<a.end;}
function suppressOverlaps(hits){const kept=[];for(const hit of hits){const conflict=kept.find(k=>overlaps(hit,k));if(!conflict){kept.push(hit);continue;}const hitLen=hit.end-hit.index,keepLen=conflict.end-conflict.index;if(hitLen>keepLen){const i=kept.indexOf(conflict);kept.splice(i,1,hit);}}return kept.sort((a,b)=>a.index-b.index);}
function isIataAlias(hit){return hit.name===hit.code.toLowerCase();}
function departureCueBefore(t,index){const before=t.slice(Math.max(0,index-42),index);return /(?:^|\s)(?:ab|von|abflug(?:hafen)?|start(?:en)?\s+ab|fliegen\s+ab|flug\s+ab|departure\s+from)\s+(?:[a-z/-]+\s*(?:,|\/|oder|und)\s*)*$/i.test(before);}
function connectedToDeparture(t,hit,accepted){if(departureCueBefore(t,hit.index))return true;if(isIataAlias(hit)){const before=t.slice(Math.max(0,hit.index-8),hit.index);if(/\b(?:ab|von)\s*$/i.test(before))return true;}if(!accepted.length)return false;const prev=accepted[accepted.length-1],between=t.slice(prev.end,hit.index);return /^\s*(?:,|\/|\+|\bund\b|\boder\b)\s*$/i.test(between);}
function parseDepartures(text){const t=norm(text),out=[],accepted=[],hits=suppressOverlaps(airportHits(t));for(const hit of hits){if(out.includes(hit.code))continue;if(!connectedToDeparture(t,hit,accepted))continue;out.push(hit.code);accepted.push(hit);}return out;}
function mentionsDeparture(text){const t=norm(text);return /\b(?:ab|von|abflug(?:hafen)?|start(?:en)?\s+ab|fliegen\s+ab|flug\s+ab)\b/.test(t);}
function repairAnalysis(text){const codes=parseDepartures(text),hits=airportHits(text),root=document.getElementById('noreyoAi556Result');if(!root||(!mentionsDeparture(text)&&!hits.length))return false;const groups=[...root.querySelectorAll('.noreyo-v556-group')];const travel=groups.find(g=>/reise/i.test(g.querySelector('.noreyo-v556-grouplabel')?.textContent||''));if(!travel)return false;const chips=travel.querySelector('.noreyo-v556-chips');if(!chips)return false;[...chips.querySelectorAll('.noreyo-v556-chip')].forEach(chip=>{if(/^Abflug\s*·/i.test(String(chip.textContent||'').replace(/^✓\s*/,'')))chip.remove();});if(codes.length){const chip=document.createElement('span');chip.className='noreyo-v556-chip';chip.innerHTML='<i>✓</i>Abflug · '+codes.join(' / ');chips.appendChild(chip);}return true;}
function snapshotAirports(){try{return Array.isArray(searchState?.airports)?searchState.airports.map(String):[];}catch(_){return[];}}
function setAirports(codes){try{if(typeof searchState==='undefined'||!searchState)return false;const old=Array.isArray(searchState.airports)?searchState.airports.map(String):[];if(old.length===codes.length&&old.every((v,i)=>v===codes[i]))return false;searchState.airports=codes.slice();try{updateSearchUI?.();}catch(_){}try{persistState?.();}catch(_){}return true;}catch(_){return false;}}
function reconcile(text,before){const codes=parseDepartures(text),hits=airportHits(text);if(codes.length)return setAirports(codes);if(hits.length&&!mentionsDeparture(text))return setAirports(Array.isArray(before)?before:[]);return false;}
function inputText(){return document.getElementById('noreyoAi556Text')?.value||'';}
function onAnalyze(e){if(!e.target?.closest?.('.noreyo-v556-analyze'))return;const text=inputText();setTimeout(()=>repairAnalysis(text),160);}
function onApply(e){if(!e.target?.closest?.('.noreyo-v556-apply'))return;const text=inputText(),before=snapshotAirports();setTimeout(()=>setTimeout(()=>reconcile(text,before),0),0);}
document.addEventListener('click',onAnalyze,true);document.addEventListener('click',onApply,true);
window.NOREYO_V800=Object.freeze({BUILD,defs,norm,airportHits,overlaps,suppressOverlaps,departureCueBefore,connectedToDeparture,parseDepartures,mentionsDeparture,repairAnalysis,snapshotAirports,setAirports,reconcile});
})();