/* NOREYO V5.92 — family parser/state safety, isolated from premium V5.77 discovery */
(function(){
'use strict';
const BUILD='5.92';
let pendingFamily=null,adultSnapshot=null;
function norm(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss');}
function num(v){const m={ein:1,eine:1,einen:1,einem:1,einer:1,zwei:2,drei:3,vier:4,fuenf:5,funf:5,sechs:6,sieben:7,acht:8,neun:9};const s=norm(v).trim();return /^\d+$/.test(s)?Number(s):(m[s]??null);}
function explicitAdults(text){const t=norm(text);return /\bzu zweit\b/.test(t)||/\b(?:[1-9]|ein(?:e|en|em|er)?|zwei|drei|vier|fuenf|funf|sechs|sieben|acht|neun)\s+(?:erwachsen(?:e|er|en)?|personen?|reisende)\b/.test(t);}
function parseAdults(text){const t=norm(text);let m=t.match(/\b([1-9]|ein(?:e|en|em|er)?|zwei|drei|vier|fuenf|funf|sechs|sieben|acht|neun)\s+(?:erwachsen(?:e|er|en)?|personen?|reisende)\b/);if(m)return num(m[1]);if(/\bzu zweit\b/.test(t))return 2;return null;}
function noChildren(text){const t=norm(text);return /\b(?:ohne|keine|kein)\s+(?:kinder|kind|babys?|sohn|tochter)\b/.test(t)||/\bnur\s+erwachsene\b/.test(t);}
function parseCount(text){const t=norm(text);if(noChildren(t))return 0;let m=t.match(/\b([1-8]|ein(?:e|en|em|er)?|zwei|drei|vier|fuenf|funf|sechs|sieben|acht)\s+(?:kinder|kindern|kind|babys?)\b/);if(m)return num(m[1]);if(/\b(?:mit\s+)?(?:einem\s+)?baby\b/.test(t))return 1;return null;}
function addAge(out,v){const n=Number(v);if(Number.isInteger(n)&&n>=0&&n<=17)out.push(n);}
function parseAges(text){const t=norm(text),out=[];let m;for(const re of [/(?:kinder|kindern|kinderalter|alter der kinder)[^.!?;]{0,55}?(\d{1,2}(?:\s*(?:,|und|&|\/)\s*\d{1,2})+)(?:\s*jahre?)?/g,/(?:mit|und)\s+(\d{1,2}(?:\s*(?:,|und|&|\/)\s*\d{1,2})+)\s*jahre?(?:\s+alt)?/g])while((m=re.exec(t)))for(const n of(m[1].match(/\d{1,2}/g)||[]))addAge(out,n);if(out.length)return out;const seg=(t.match(/\b(?:kinder|kindern|kind|babys?)\b[^.!?;]{0,80}/)||[''])[0];if(seg){const years=[...seg.matchAll(/(\d{1,2})\s*(?:jahre?|jahr|j\.)\b/g)].map(x=>Number(x[1]));if(years.length){years.forEach(n=>addAge(out,n));return out;}const months=seg.match(/(\d{1,2}(?:\s*(?:,|und|&|\/)\s*\d{1,2})+)\s*(?:monate?|monat)\b/);if(months){for(const _ of(months[1].match(/\d{1,2}/g)||[]))addAge(out,0);return out;}}const baby=t.match(/\bbaby[^.!?;]{0,24}?(\d{1,2})\s*(?:monate?|monat)\b/);if(baby){addAge(out,0);return out;}const one=t.match(/\b(?:kinder|kindern|kind|baby)\b[^.!?;]{0,24}?(\d{1,2})\s*(?:jahre?|jahr|j\.)\b/);if(one)addAge(out,one[1]);return out;}
function parseFamily(text){const t=norm(text),adults=parseAdults(t),count=parseCount(t),ages=parseAges(t);const intent=count!==null||ages.length>0||/\b(?:kinder|kindern|kind|babys?|familie)\b/.test(t);if(!intent)return null;if(count===0)return{adults,count:0,ages:[],complete:true,errors:[]};const c=count===null?ages.length:count,errors=[];if(!c)errors.push('Kinderanzahl fehlt');if(ages.length!==c)errors.push(`Bitte Alter für ${c||'alle'} Kinder angeben`);if(adults&&adults+c>9)errors.push('Maximal 9 Reisende pro Suche');if(adults&&ages.filter(v=>v<=1).length>adults)errors.push('Maximal ein Kleinkind unter 2 pro Erwachsenem');return{adults,count:c,ages,complete:c>0&&ages.length===c&&!errors.length,errors};}
function state(){try{return typeof searchState!=='undefined'&&searchState?searchState:null;}catch(_){return null;}}
function refresh(){try{if(typeof updateSearchUI==='function')updateSearchUI();}catch(_){}try{if(typeof persistState==='function')persistState();}catch(_){} }
function naturalText(){return document.querySelector('#discover [data-v574-text]')?.value||document.querySelector('#discover [data-v571-text]')?.value||document.getElementById('noreyoAi556Text')?.value||'';}
function familySatisfiedByState(f){const s=state();if(!f||!s||f.complete)return false;const a=Math.round(Number(s.adults)),ages=Array.isArray(s.childAges)?s.childAges.map(Number):[];if(!Number.isInteger(a)||a<1||a>9)return false;if(f.adults&&a!==f.adults)return false;if(!f.count||ages.length!==f.count)return false;return a+ages.length<=9&&ages.every(v=>Number.isInteger(v)&&v>=0&&v<=17)&&ages.filter(v=>v<=1).length<=a;}
function applyFamily(text=naturalText()){const f=parseFamily(text),s=state();if(!f){pendingFamily=null;return f;}if(f.complete&&s){if(f.adults)s.adults=Math.max(1,Math.min(9,f.adults));s.childAges=f.ages.slice();pendingFamily=null;refresh();return f;}if(familySatisfiedByState(f)){pendingFamily=null;return f;}pendingFamily={...f,createdAt:Date.now()};return f;}
function travellersValid(){const s=state();if(!s)return false;const a=Math.round(Number(s.adults)),ages=Array.isArray(s.childAges)?s.childAges.map(Number):[];return Number.isInteger(a)&&a>=1&&a<=9&&a+ages.length<=9&&ages.every(v=>Number.isInteger(v)&&v>=0&&v<=17)&&ages.filter(v=>v<=1).length<=a;}
function pendingResolved(){return !!pendingFamily&&familySatisfiedByState(pendingFamily);}
function validateBeforeSearch(){if(!travellersValid())return'Bitte die Reisenden vollständig prüfen.';if(pendingFamily&&!pendingResolved())return pendingFamily.errors[0]||'Bitte die Kinderalter ergänzen.';if(pendingResolved())pendingFamily=null;return'';}
function onAiApplyCapture(e){const btn=e.target instanceof Element?e.target.closest('.noreyo-v556-apply'):null;if(!btn)return;const text=naturalText(),s=state();adultSnapshot=!explicitAdults(text)&&Number.isInteger(Math.round(Number(s?.adults)))?Math.round(Number(s.adults)):null;setTimeout(()=>{applyFamily(text);if(adultSnapshot&&s&&Math.round(Number(s.adults))!==adultSnapshot){s.adults=adultSnapshot;refresh();}adultSnapshot=null;},0);}
function install(){document.addEventListener('click',onAiApplyCapture,true);window.addEventListener('pagehide',()=>{adultSnapshot=null;},{passive:true});}
window.NOREYO_V592=Object.freeze({BUILD,parseFamily,explicitAdults,familySatisfiedByState,applyFamily,validateBeforeSearch,travellersValid,pendingResolved,get pendingFamily(){return pendingFamily;}});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();