/* NOREYO V7.24 — generation-owned unified multi transport.
   Extends V7.21 so a fallback retry is launched only if the request still
   belongs to the current user search generation after the first response. */
(function(){
'use strict';
const BUILD='7.24';
function inputUrl(input){if(typeof input==='string')return input;try{if(typeof Request!=='undefined'&&input instanceof Request)return input.url||'';}catch(_){}return'';}
function isSearchTravel(input){return inputUrl(input).includes('/functions/v1/search-travel');}
function parseText(text){if(typeof text!=='string'||!text.trim())return null;try{return JSON.parse(text);}catch(_){return null;}}
async function rawBody(input,init){if(typeof init?.body==='string')return parseText(init.body);try{if(typeof Request!=='undefined'&&input instanceof Request){if(input.bodyUsed)return null;return parseText(await input.clone().text());}}catch(_){}return null;}
function isFlight(raw){return String(raw?.action||'').trim().toLowerCase()==='flight';}
function isMulti(raw){return !isFlight(raw)&&Array.isArray(raw?.occupancies)&&raw.occupancies.length>1;}
function validHotelId(value){if(typeof value!=='string'&&typeof value!=='number')return false;return /^[A-Za-z0-9][A-Za-z0-9._:/-]{0,127}$/.test(String(value).trim());}
function cleanHotelIds(ids){if(!Array.isArray(ids))return[];const out=[];for(const value of ids){if(!validHotelId(value))continue;const id=String(value).trim();if(!out.includes(id))out.push(id);if(out.length>=20)break;}return out;}
function destinationFallbackIata(){try{const key=typeof normalizeLookup==='function'?normalizeLookup(dest):String(dest||'').trim().toLowerCase();return String(destinationIata?.[key]||destinationIata?.[String(dest||'').toLowerCase()]||'').toUpperCase();}catch(_){return'';}}
function sanitize(raw){const body={...(raw||{})};body.occupancies=(Array.isArray(body.occupancies)?body.occupancies:[]).map(occ=>({adults:Number(occ?.adults),children:Array.isArray(occ?.children)?occ.children.map(Number):[]}));body.currency='EUR';body.guestNationality='DE';const ids=cleanHotelIds(body.hotelIds);if(ids.length)body.hotelIds=ids;else delete body.hotelIds;if(!body.hotelIds?.length){let iata=String(body.iataCode||'').trim().toUpperCase();if(!/^[A-Z]{3}$/.test(iata))iata=destinationFallbackIata();if(/^[A-Z]{3}$/.test(iata))body.iataCode=iata;else delete body.iataCode;}else delete body.iataCode;if(body.maxRatesPerHotel!==undefined)body.maxRatesPerHotel=Math.max(1,Math.min(10,Math.round(Number(body.maxRatesPerHotel)||3)));if(body.limit!==undefined)body.limit=Math.max(1,Math.min(100,Math.round(Number(body.limit)||40)));return body;}
function minimal(raw){const clean=sanitize(raw),out={occupancies:clean.occupancies,currency:'EUR',guestNationality:'DE',checkin:clean.checkin,checkout:clean.checkout,includeHotelData:true,roomMapping:true,maxRatesPerHotel:Math.max(1,Math.min(10,Math.round(Number(clean.maxRatesPerHotel)||3))),limit:Math.max(1,Math.min(100,Math.round(Number(clean.limit)||40)))};if(clean.hotelIds?.length)out.hotelIds=clean.hotelIds;else if(/^[A-Z]{3}$/.test(String(clean.iataCode||'')))out.iataCode=clean.iataCode;return out;}
function headersFor(input,init){try{if(init?.headers)return new Headers(init.headers);if(typeof Request!=='undefined'&&input instanceof Request)return new Headers(input.headers);}catch(_){}return new Headers();}
function requestFor(input,init,raw){const headers=headersFor(input,init);if(!headers.has('content-type'))headers.set('content-type','application/json');const options={...(init||{}),headers,body:JSON.stringify(raw)};if(typeof Request!=='undefined'&&input instanceof Request)return new Request(input,options);return new Request(new URL(String(input),location.href).href,options);}
async function retryable(response){if(!response||response.ok)return false;if(response.status!==400&&response.status!==422)return false;try{const payload=await response.clone().json();if(String(payload?.error?.code||'')==='INVALID_SEARCH_REQUEST')return false;const message=String(payload?.error?.message||payload?.message||'');return /required request field|wrong input|missing/i.test(message);}catch(_){return false;}}
function visible(el){if(!el)return false;try{if(el.hidden)return false;const style=getComputedStyle(el);if(style.display==='none'||style.visibility==='hidden')return false;return !!(el.offsetWidth||el.offsetHeight||el.getClientRects?.().length);}catch(_){return true;}}
function searchButton(){const active=document.querySelector('.view.active'),selectors='.noreyo-v541-booking-cta,.liveSearchButton,.search-card .primary',activeButtons=active?[...active.querySelectorAll(selectors)]:[],all=[...activeButtons,...document.querySelectorAll(selectors)];return all.find(visible)||all[0]||null;}
function rearmGuard(){try{const api=window.NOREYO_V607;if(!api?.startGuard||api.active||api.authoritativeMode?.()===false)return false;return !!api.startGuard(searchButton());}catch(_){return false;}}
function generation(){try{return Number(window.NOREYO_V723?.currentEpoch?.())||0;}catch(_){return 0;}}
function stillOwned(epoch){try{const api=window.NOREYO_V723;if(!api?.owned)return true;return !!api.owned(epoch);}catch(_){return true;}}
function install(){try{if(typeof window.fetch!=='function'||window.fetch.__noreyoV724)return false;const prior=window.fetch.bind(window);const wrapped=async function(input,init){if(!isSearchTravel(input))return prior(input,init);const epoch=generation();const raw=await rawBody(input,init);if(!isMulti(raw))return prior(input,init);let first;try{first=requestFor(input,init,sanitize(raw));}catch(_){return prior(input,init);}const response=await prior(first);if(!(await retryable(response)))return response;if(!stillOwned(epoch))return response;rearmGuard();if(!stillOwned(epoch)){try{window.NOREYO_V607?.releaseGuard?.('retry-superseded');}catch(_){}return response;}let second;try{second=requestFor(input,init,minimal(raw));}catch(_){return response;}return prior(second);};wrapped.__noreyoV724=true;window.fetch=wrapped;return true;}catch(_){return false;}}
install();window.addEventListener('pageshow',install,{passive:true});
window.NOREYO_V724=Object.freeze({BUILD,inputUrl,isSearchTravel,parseText,rawBody,isFlight,isMulti,validHotelId,cleanHotelIds,sanitize,minimal,headersFor,requestFor,retryable,visible,searchButton,rearmGuard,generation,stillOwned,install});
})();